Repository yunionio/cloudpods-operator, pull requests merged in 2019-12, with the labels that each got.

#2 host operator
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/base_control.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster/onecloud_cluster_controller.go
  pkg/controller/daemonset_control.go
  pkg/manager/component/component.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/sync.go
  pkg/manager/component/utils.go
Labels: size/XL

#6 change service node port
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/keystone.go
  pkg/manager/component/web.go
  pkg/manager/config/config.go
Labels: size/M

#5 support baremetal
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/component.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
Labels: size/L

#7 bugfix: set host work dir
  pkg/manager/component/host.go
Labels: size/XS

#9 fix: 支持cloudevent组件
  go.mod
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/component.go
Labels: size/L

#10 onecloud controller set affinity
  pkg/apis/constants/constants.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/component.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
Labels: size/L

#11 feature: add s3gateay component
  Makefile
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/s3gateway.go
  pkg/util/onecloud/onecloud.go
Labels: approved, lgtm, size/L

#12 use /etc/yunion rather than /etc
  pkg/manager/component/utils.go
Labels: size/XS

#13 feature: add devtool component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/host.go
Labels: approved, lgtm, size/L

#14 use rolling update strategy for non hostNetwork deployment
  pkg/manager/component/component.go
Labels: approved, size/XS

#15 add cronjob support
  docs/intro.md
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_controller.go
  pkg/controller/cronjob_control.go
  pkg/manager/component/component.go
  pkg/manager/component/sync.go
  pkg/manager/component/utils.go
Labels: size/L

#16 feature: meter support
  images/onecloud-operator/Dockerfile
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/meter.go
Labels: size/L

#17 add imageStatus
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster/onecloud_cluster_controller.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/component.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/sync.go
  pkg/manager/component/sync_test.go
  pkg/manager/component/yunionagent.go
Labels: size/L
