Repository yunionio/cloudpods-operator, pull requests merged in 2020-06, with the labels that each got.

#163 set cronjob default attributes
  pkg/manager/component/component.go
Labels: size/XS

#164 Automated cherry pick of #163: set cronjob default attributes
  pkg/manager/component/component.go
Labels: size/XS

#165 Automated cherry pick of #163: set cronjob default attributes
  pkg/manager/component/component.go
Labels: size/XS

#166 bugfix: remove put/del key on liveness probe
  pkg/manager/component/etcd.go
Labels: size/S

#167 Automated cherry pick of #166: remove put/del key on liveness probe
  pkg/manager/component/etcd.go
Labels: size/S

#168 operator增加itsm服务
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/itsm.go
Labels: size/L

#169 Automated cherry pick of #168: operator增加itsm服务
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/itsm.go
Labels: size/L

#171 Automated cherry pick of #170: not register azure classic host data
  pkg/controller/onecloud_control.go
Labels: approved, lgtm, size/XS

#170 not register azure classic host data
  pkg/controller/onecloud_control.go
Labels: approved, lgtm, size/XS

#172 itsm: limit memory to 1G
  pkg/manager/component/itsm.go
Labels: approved, lgtm, size/XS

#173 Automated cherry pick of #172: itsm: limit memory to 1G
  pkg/manager/component/itsm.go
Labels: approved, lgtm, size/XS

#174 fix: change command of init container for oso
  pkg/manager/component/service_operator.go
Labels: size/XS

#175 itsm endpoint注册为http请求
  pkg/controller/onecloud_control.go
  pkg/manager/component/itsm.go
Labels: size/M

#176 Automated cherry pick of #175: itsm endpoint注册为http请求
  pkg/controller/onecloud_control.go
  pkg/manager/component/itsm.go
Labels: size/M

#180 fix: Change api prefix '/api/v1' as 'api/v1'
  pkg/manager/component/notify.go
Labels: size/XS

#178 add billing service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/billing.go
  pkg/manager/component/component.go
Labels: approved, lgtm, size/L

#181 fix:优化manifest example
  manifests/example-onecloud-cluster.yaml
  manifests/onecloud-operator.yaml
Labels: size/XS

#179 new pvc name with storage class
  pkg/manager/component/component.go
Labels: size/S

#183 fix etcd defrag
  pkg/manager/component/etcd.go
Labels: size/XS

#184 Automated cherry pick of #183: fix etcd defrag
  pkg/manager/component/etcd.go
Labels: size/XS

#182 telegraf as daemonset
  Makefile
  README.md
  cmd/telegraf-init/main.go
  images/telegraf-init/Dockerfile
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/telegraf.go
Labels: size/L

#186 fix: Change `xxIntervalxx` type from 'int' to '*int'
  pkg/manager/component/service_operator.go
Labels: size/XS

#185 feature: host image as daemonset
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
Labels: size/L

#189 fix: check before doing perform_public for roles and policies
  pkg/controller/onecloud_policy.go
Labels: approved, lgtm, size/S

#190 feature: add cloudid service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/component.go
Labels: size/L

#191 Automated cherry pick of #190: feature: add cloudid service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/component.go
Labels: size/L

#192 check etcd dbsize, do compact and defrag
  pkg/manager/component/etcd.go
Labels: size/M

#193 Automated cherry pick of #192: check etcd dbsize, do compact and defrag
  pkg/manager/component/etcd.go
Labels: size/M
