Repository yunionio/cloudpods-operator, pull requests merged in 2020-12, with the labels that each got.

#352 chore(monitor): add new service: suggestion
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/suggestion.go
Labels: size/M

#353 Automated cherry pick of #352: chore(monitor): add new service: suggestion
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/suggestion.go
Labels: size/M

#354 fix(telegraf): fix collect disk measurements
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/M

#355 Automated cherry pick of #354: fix(telegraf): fix collect disk measurements
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/M

#356 feat:(monitor): update system monitor alert when alert has diff info
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#357 Automated cherry pick of #356: feat:(monitor): update system monitor alert when alert has diff info
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#360 bugfix(suggestion): fix err when suggestion syncConfigMap
  pkg/manager/component/suggestion.go
Labels: size/XS

#361 Automated cherry pick of #360: bugfix(suggestion): fix err when suggestion syncConfigMap
  pkg/manager/component/suggestion.go
Labels: size/XS

#358 feat(framework): support multi zone
  go.mod
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
  pkg/label/label.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
Labels: size/XXL

#362 Automated cherry pick of #358: feat(framework): support multi zone
  go.mod
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
  pkg/label/label.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
Labels: size/XXL

#363 Automated cherry pick of #358: feat(framework): support multi zone
  go.mod
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
  pkg/label/label.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
Labels: size/XXL

#365 Hotfix/qj rebase nocloud 20201214
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster/onecloud_cluster_controller.go
  pkg/manager/certs/manager.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/billing.go
  pkg/manager/component/billingtask.go
  pkg/manager/component/component.go
  pkg/manager/component/register.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
  vendor/github.com/coreos/etcd-operator/LICENSE
  vendor/github.com/coreos/etcd-operator/NOTICE
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/backup_types.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/cluster.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/cluster_tls.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/doc.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/register.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/restore_types.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/status.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
  vendor/yunion.io/x/log/formatter.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/serversku.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/sku_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/vpcs_ovn.go
  vendor/yunion.io/x/onecloud/pkg/apis/const.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/commalert.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/metric.go
  vendor/yunion.io/x/onecloud/pkg/apis/scheduler/api.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/consts/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/consts/opslog.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/changes.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/images.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_servers.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/instance_base.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/region_base.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/vpc_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/sql.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/XXL

#367 Automated cherry pick of #366: fix: role-policy-create many unknown role-policies
  pkg/controller/onecloud_control.go
  pkg/controller/onecloud_policy.go
  pkg/controller/predefined_policies.go
Labels: lgtm, size/M

#366 fix: role-policy-create many unknown role-policies
  pkg/controller/onecloud_control.go
  pkg/controller/onecloud_policy.go
  pkg/controller/predefined_policies.go
Labels: approved, lgtm, size/M

#371 Automated cherry pick of #370: fix(monitor): system alert policy cancel description update limit
  pkg/util/onecloud/onecloud.go
Labels: approved, lgtm, size/XS

#370 fix(monitor): system alert policy cancel description update limit
  pkg/util/onecloud/onecloud.go
Labels: approved, lgtm, size/XS

#369 Automated cherry pick of #368: fix: skip create policies error
  pkg/controller/onecloud_control.go
Labels: size/S

#368 fix: skip create policies error
  pkg/controller/onecloud_control.go
Labels: size/S

#373 feat(component): remove kube-rbac-proxy
  pkg/manager/component/service_operator.go
Labels: size/S

#374 Automated cherry pick of #373: feat(component): remove kube-rbac-proxy
  pkg/manager/component/service_operator.go
Labels: size/S

#372 defaults: using openvswitch image of tag 2.10.5-1
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: lgtm, size/XS
