Repository yunionio/cloudpods-operator, pull requests merged in 2020-09, with the labels that each got.

#259 Automated cherry pick of #258: - etcd clean failed state pods
  pkg/manager/component/etcd.go
  pkg/manager/component/host-deployer.go
Labels: approved, lgtm, size/M

#258 etcd && host-deployer misc fix
  pkg/manager/component/etcd.go
  pkg/manager/component/host-deployer.go
Labels: approved, lgtm, size/M

#260 buildx for onecloud-operator
  Makefile
  images/onecloud-operator/Dockerfile
  images/telegraf-init/Dockerfile
  scripts/docker_push.sh
Labels: approved, lgtm, size/L

#261 Automated cherry pick of #260: buildx for onecloud-operator
  Makefile
  images/onecloud-operator/Dockerfile
  images/telegraf-init/Dockerfile
  scripts/docker_push.sh
Labels: approved, lgtm, size/L

#262 push 镜像后,拉回本地
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#263 Automated cherry pick of #262: push 镜像后,拉回本地
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#266 Automated cherry pick of #251: statusfulset set cloud affinity:
  pkg/manager/component/etcd.go
Labels: size/XS

#267 notify: remove pvc dependence
  pkg/manager/component/notify.go
Labels: size/XS

#268 Automated cherry pick of #267: notify: remove pvc dependence
  pkg/manager/component/notify.go
Labels: size/XS

#269 Automated cherry pick of #267: notify: remove pvc dependence
  pkg/manager/component/notify.go
Labels: size/XS

#270 BusyBox upgrade ,modify cloudmon timeout arg
  pkg/manager/component/cloudmon.go
Labels: approved, lgtm, size/M

#272 Automated cherry pick of #271: add flag check is failed etcd pods need delete
  cmd/controller-manager/main.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
Labels: approved, lgtm, size/XS

#271 add flag check is failed etcd pods need delete
  cmd/controller-manager/main.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
Labels: approved, lgtm, size/XS

#273 host image spec fix
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#275 Automated cherry pick of #273: host image spec fix
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#274 Automated cherry pick of #273: host image spec fix
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#276 Automated cherry pick of #270: BusyBox upgrade ,modify cloudmon timeout arg
  pkg/manager/component/cloudmon.go
Labels: approved, lgtm, size/M

#277 yunionagent: remove onecloud keyword
  pkg/controller/onecloud_control.go
Labels: size/XS

#279 billingtask add db options
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/billingtask.go
Labels: approved, lgtm, size/S

#281 Automated cherry pick of #280: pod affinity by storage class
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/service_operator.go
Labels: approved, lgtm, size/M

#282 Automated cherry pick of #280: pod affinity by storage class
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/service_operator.go
Labels: approved, lgtm, size/M

#280 pod affinity by storage class
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/service_operator.go
Labels: approved, lgtm, size/M
