Repository yunionio/cloudpods-operator, pull requests merged in 2020-05, with the labels that each got.

#135 onecloud culster fix:
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/keystone.go
  pkg/manager/component/notify.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/utils.go
Labels: size/L

#136 Automated cherry pick of #135: onecloud culster fix:
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/keystone.go
  pkg/manager/component/notify.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/utils.go
Labels: size/L

#139 web: remove unused nginx config
  pkg/manager/component/web.go
Labels: size/M

#141 set keystone url
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/loadbalancer.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/scaling_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/scaling_policy.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/snapshot_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/vpcs_ovn.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/wire.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/endpoint.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/list.go
  vendor/yunion.io/x/onecloud/pkg/apis/output.go
  vendor/yunion.io/x/onecloud/pkg/baremetal/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/compute/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_proxysettings.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/onecloud/pkg/util/netutils2/http.go
  vendor/yunion.io/x/onecloud/pkg/util/ovsutils/ovsutils.go
  vendor/yunion.io/x/onecloud/pkg/util/rbacutils/policyset.go
  vendor/yunion.io/x/onecloud/pkg/util/rbacutils/rbac.go
  vendor/yunion.io/x/onecloud/pkg/util/seclib2/tls.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/XL

#128 修改reportserver cronjob采集监控数据的间隔
  go.mod
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon_report_server.go
Labels: size/M

#129 Automated cherry pick of #128: 修改reportserver cronjob采集监控数据的间隔
  go.mod
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon-report-server.go
Labels: size/M

#130 Automated cherry pick of #128: 修改reportserver cronjob采集监控数据的间隔
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon_report_server.go
Labels: size/M

#131 Automated cherry pick of #128: 修改reportserver cronjob采集监控数据的间隔
  go.mod
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon_report_server.go
Labels: size/M

#143 Create cronjob for monitor of Host :VMware and ZStack
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/component.go
Labels: size/L

#144 Automated cherry pick of #143: 增加宿主机的监控查询的cronjob
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/component.go
Labels: size/L

#145 Automated cherry pick of #143: 增加宿主机的监控查询的cronjob
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/component.go
Labels: size/L

#146 Automated cherry pick of #143: 增加宿主机的监控查询的cronjob
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/component.go
Labels: size/L

#149 first create policy
  pkg/controller/onecloud_control.go
Labels: size/XS

#150 Automated cherry pick of #149: first create policy
  pkg/controller/onecloud_control.go
Labels: size/XS

#147 etcd operator fix
  pkg/manager/component/etcd.go
Labels: size/M

#151 Automated cherry pick of #147: fix etcd arguments
  pkg/manager/component/etcd.go
Labels: size/M

#152 etcd operator fix
  pkg/manager/component/etcd.go
Labels: size/L

#153 Automated cherry pick of #152: etcd operator fix
  pkg/manager/component/etcd.go
Labels: size/L

#158 etcd cluster default use version 3.4.6
  pkg/apis/constants/constants.go
Labels: size/XS

#159 Automated cherry pick of #158: etcd cluster default use version 3.4.6
  pkg/apis/constants/constants.go
Labels: size/XS

#154 bugfix：宿主机监控没有默认值注入的函数
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#156 Automated cherry pick of #154: bugfix：宿主机监控没有默认值注入的函数
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#155 Automated cherry pick of #154: bugfix：宿主机监控没有默认值注入的函数
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#157 Automated cherry pick of #154: bugfix：宿主机监控没有默认值注入的函数
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#161 Automated cherry pick of #135: onecloud culster fix:
  pkg/apis/onecloud/v1alpha1/onecloudcluster.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/keystone.go
  pkg/manager/component/notify.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/utils.go
Labels: size/L

#160 feat: Add support for onecloud-resource-operator
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/service_operator.go
Labels: size/L

#162 defaults: using openvswitch image of tag 2.10.4-0
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS
