Repository yunionio/cloudpods-operator, pull requests merged in 2020-08, with the labels that each got.

#239 billingtask volume fix
  pkg/manager/component/billingtask.go
Labels: approved, lgtm

#242 itsm 开启https
  pkg/controller/onecloud_control.go
Labels: approved, lgtm, size/XS

#241 cloudmon deployment increate cloudaccount monitor config:
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudmon.go
  pkg/util/onecloud/onecloud.go
Labels: approved, lgtm, size/M

#240 Add workwx and workwx-robot for notify
  pkg/manager/component/notify.go
Labels: approved, lgtm, size/S

#243 web: add dashboard overview
  pkg/manager/component/component.go
  pkg/manager/component/sync.go
  pkg/manager/component/web.go
Labels: approved, lgtm, size/M

#245 Automated cherry pick of #244: fix baremetal storage size
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#246 Automated cherry pick of #244: fix baremetal storage size
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#247 Automated cherry pick of #244: fix baremetal storage size
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#248 crontab timeout
  pkg/manager/component/cloudmon.go
Labels: size/M

#250 update host image default spec
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/host-image.go
Labels: size/S

#251 statusfulset set cloud affinity
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
Labels: size/M

#252 remove api/v1 from notify endpoint url
  pkg/manager/component/notify.go
Labels: approved, lgtm

#253 feature: replace cloud affinity preferred by required
  pkg/manager/component/component.go
Labels: approved, lgtm

#254 Automated cherry pick of #253: replace cloud affinity preferred by required
  pkg/manager/component/component.go
Labels: approved, lgtm, size/XS

#256 Automated cherry pick of #255: deployment with pvc not set node affinity
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/notify.go
  pkg/manager/component/vpcagent.go
Labels: approved, lgtm, size/M

#255 deployment with pvc not set node affinity
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/notify.go
  pkg/manager/component/vpcagent.go
Labels: approved, lgtm, size/M

#257 Automated cherry pick of #255: deployment with pvc not set node affinity
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
  pkg/manager/component/notify.go
  pkg/manager/component/vpcagent.go
Labels: approved, lgtm
