Repository yunionio/cloudpods-operator, pull requests merged in 2020-03, with the labels that each got.

#42 host: mark those host services as unneeded on host system
  pkg/manager/component/host.go
Labels: lgtm, size/XS

#43 Automated cherry pick of #42: host: mark those host services as unneeded on host system
  pkg/manager/component/host.go
Labels: size/XS

#45 add monitor and remove kapacitor
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/kapacitor.go
  pkg/manager/component/monitor.go
Labels: size/L

#46 Automated cherry pick of #45: add monitor and remove kapacitor
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/kapacitor.go
  pkg/manager/component/monitor.go
Labels: size/L

#50 defaults: openvswitch: default to using 2.9.6-2
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
Labels: size/S

#51 Automated cherry pick of #50: defaults: openvswitch: default to using 2.9.6-2
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
Labels: size/S

#52 daemonset use rolling updateStrategy
  pkg/manager/component/component.go
Labels: lgtm, size/XS

#53 Automated cherry pick of #52: daemonset use rolling updateStrategy
  pkg/manager/component/component.go
Labels: size/XS

#54 Automated cherry pick of #52: daemonset use rolling updateStrategy
  pkg/manager/component/component.go
Labels: size/XS

#55 feat(notify): Add one driver and change some config
  pkg/manager/component/notify.go
Labels: size/S

#59 use distribution pkg parse image
  go.mod
  go.sum
  pkg/manager/component/sync.go
  pkg/manager/component/sync_test.go
  pkg/util/image/reference.go
  pkg/util/image/reference_test.go
  vendor/github.com/docker/distribution/AUTHORS
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/opencontainers/go-digest/.pullapprove.yml
  vendor/github.com/opencontainers/go-digest/.travis.yml
  vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
  vendor/github.com/opencontainers/go-digest/LICENSE.code
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/MAINTAINERS
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/verifiers.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/cloudprovider/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_groups.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
Labels: lgtm, size/XXL

#60 Automated cherry pick of #59: use distribution pkg parse image
  go.mod
  go.sum
  pkg/manager/component/sync.go
  pkg/manager/component/sync_test.go
  pkg/util/image/reference.go
  pkg/util/image/reference_test.go
  vendor/github.com/docker/distribution/AUTHORS
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/opencontainers/go-digest/.pullapprove.yml
  vendor/github.com/opencontainers/go-digest/.travis.yml
  vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
  vendor/github.com/opencontainers/go-digest/LICENSE.code
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/MAINTAINERS
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/verifiers.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/cloudprovider/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_groups.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
Labels: lgtm, size/XXL

#61 feat(notify): Add one driver and change some config
  pkg/manager/component/notify.go
Labels: size/XS

#56 report-server 主机信息监控-aliyun、huawei
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon-report-server.go
  pkg/manager/component/component.go
  vendor/modules.txt
Labels: size/L

#58 Automated cherry pick of #56: report-server operator 创建Cronjob功能
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon-report-server.go
  pkg/manager/component/component.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
Labels: size/L

#57 Automated cherry pick of #56: report-server operator 创建Cronjob功能
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon-report-server.go
  pkg/manager/component/component.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_groups.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
Labels: size/XXL

#62 fix 3.0 cherry-pick code
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/component.go
Labels: size/S

#63 update baremetal default options
  pkg/manager/component/baremetal.go
Labels: size/XS

#64 Automated cherry pick of #63: update baremetal default options
  pkg/manager/component/baremetal.go
Labels: size/XS

#65 Automated cherry pick of #63: update baremetal default options
  pkg/manager/component/baremetal.go
Labels: size/XS

#66 region use onecloud service account
  pkg/apis/constants/constants.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/region.go
Labels: size/S

#67 Automated cherry pick of #66: region use onecloud service account
  pkg/apis/constants/constants.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/region.go
Labels: size/S

#71 Automated cherry pick of #69: use cached auth session
  cmd/controller-manager/main.go
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/manager/component/utils.go
  vendor/modules.txt
  vendor/yunion.io/x/log/log.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_bucket_options.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XL

#73 Automated cherry pick of #72: fix auth logic
  pkg/controller/onecloud_control.go
  pkg/manager/component/utils.go
Labels: size/XS

#74 Automated cherry pick of #72: fix auth logic
  pkg/controller/onecloud_control.go
  pkg/manager/component/utils.go
Labels: size/XS

#75 add exists non-project user in project
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#76 Automated cherry pick of #75: add exists non-project user in project
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#77 Automated cherry pick of #75: add exists non-project user in project
  pkg/manager/component/utils.go
Labels: approved, lgtm, size/M

#78 feat: Add feishu-robot and dingtalk-robot for notify.
  pkg/manager/component/notify.go
Labels: size/S

#80 Automated cherry pick of #79: host: run dir use bidirectional mount
  pkg/manager/component/utils.go
Labels: size/XS

#81 Automated cherry pick of #79: host: run dir use bidirectional mount
  pkg/manager/component/utils.go
Labels: size/XS

#82 add region dns component
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudmon_ping.go
  pkg/manager/component/cloudmon_report_server.go
  pkg/manager/component/cloudmon_report_usage.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/consts.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/doc.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/proxy.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_sku.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/storage.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/scheduler/api.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/errors.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/joint.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/resource.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_proxysettings.go
  vendor/yunion.io/x/onecloud/pkg/util/httputils/httputils.go
Labels: lgtm, size/XL

#83 Automated cherry pick of #82: add region dns component
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudmon_ping.go
  pkg/manager/component/cloudmon_report_server.go
  pkg/manager/component/cloudmon_report_usage.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/consts.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/doc.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/proxy.go
  vendor/yunion.io/x/onecloud/pkg/apis/cloudcommon/proxy/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_sku.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/storage.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/scheduler/api.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/errors.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/joint.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/resource.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_contacts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_proxysettings.go
  vendor/yunion.io/x/onecloud/pkg/util/httputils/httputils.go
Labels: size/XL

#84 fix: auto config notify email_verify_url_path
  pkg/manager/component/notify.go
Labels: size/XS

#86 keystone: always reset default system user password
  pkg/manager/component/keystone.go
Labels: size/XS

#87 Automated cherry pick of #86: keystone: always reset default system user password
  pkg/manager/component/keystone.go
Labels: size/XS

#88 Automated cherry pick of #86: keystone: always reset default system user password
  pkg/manager/component/keystone.go
Labels: size/XS
