Repository yunionio/cloudpods-operator, pull requests merged in 2020-11, with the labels that each got.

#317 限制 client_header_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: size/XS

#318 Automated cherry pick of #317: 限制 client_header_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: size/XS

#319 Automated cherry pick of #317: 限制 client_header_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: size/XS

#320 限制 client_body_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: size/XS

#322 Automated cherry pick of #320: 限制 client_body_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: size/XS

#323 限制 client_body_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: lgtm, size/XS

#324 Automated cherry pick of #323: 限制 client_body_timeout 时长，预防慢攻击
  pkg/manager/component/web.go
Labels: lgtm, size/XS

#329 ce edition should not deploy meter
  pkg/manager/component/meter.go
Labels: size/XS

#330 Automated cherry pick of #329: ce edition should not deploy meter
  pkg/manager/component/meter.go
Labels: size/XS

#331 Automated cherry pick of #329: ce edition should not deploy meter
  pkg/manager/component/meter.go
Labels: size/XS

#332 etcd add pod anti affinity
  pkg/manager/component/etcd.go
Labels: size/S

#333 Automated cherry pick of #332: etcd add pod anti affinity
  pkg/manager/component/etcd.go
Labels: size/S

#334 Automated cherry pick of #332: etcd add pod anti affinity
  pkg/manager/component/etcd.go
Labels: size/S

#335 fix: add more dashboard default policies
  pkg/controller/predefined_policies.go
Labels: size/S

#341 Automated cherry pick of #340: feature(keystone): add default member role
  pkg/controller/onecloud_policy.go
  pkg/controller/predefined_policies.go
Labels: size/M

#340 feature(keystone): add default member role
  pkg/controller/onecloud_policy.go
  pkg/controller/predefined_policies.go
Labels: approved, lgtm, size/M

#328 web: add docs image
  pkg/manager/component/web.go
Labels: size/L

#344 Automated cherry pick of #328: web: add docs image
  pkg/manager/component/web.go
Labels: size/L

#342 feat(operator): add nodata alert policy
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/locales/locales.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/schedtag.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/commalert.go
  vendor/yunion.io/x/onecloud/pkg/compute/options/options.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/onecloud/pkg/util/seclib2/seclib.go
Labels: size/XXL

#343 Automated cherry pick of #342: feat(operator): add nodata alert policy
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/locales/locales.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/schedtag.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/commalert.go
  vendor/yunion.io/x/onecloud/pkg/compute/options/options.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/onecloud/pkg/util/seclib2/seclib.go
Labels: size/XXL

#349 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/bucket.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/networkaddress.go
  vendor/yunion.io/x/onecloud/pkg/apis/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/list.go
  vendor/yunion.io/x/onecloud/pkg/apis/output.go
  vendor/yunion.io/x/onecloud/pkg/apis/scheduler/api.go
  vendor/yunion.io/x/onecloud/pkg/apis/update.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_networkaddresses.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/bucket_base.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/vnic.go
  vendor/yunion.io/x/onecloud/pkg/util/stringutils2/stringutils.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/filter.go
Labels: size/L

#350 Automated cherry pick of #349: update vendor
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/bucket.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/networkaddress.go
  vendor/yunion.io/x/onecloud/pkg/apis/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/list.go
  vendor/yunion.io/x/onecloud/pkg/apis/output.go
  vendor/yunion.io/x/onecloud/pkg/apis/scheduler/api.go
  vendor/yunion.io/x/onecloud/pkg/apis/update.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_networkaddresses.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/bucket_base.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/vnic.go
  vendor/yunion.io/x/onecloud/pkg/util/stringutils2/stringutils.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/filter.go
Labels: size/L
