Repository yunionio/cloudpods-operator, pull requests merged in 2020-01, with the labels that each got.

#19 cloudmon ping cronjob
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/cloudmon-ping.go
  pkg/manager/component/component.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
  pkg/manager/component/web.go
Labels: size/L

#21 add devtool phase
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/devtool.go
  pkg/util/onecloud/onecloud.go
  pkg/util/onecloud/static.go
Labels: size/L

#22 set baremetal replicas by node counts
  pkg/controller/cluster/onecloud_cluster_controller.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/component.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host.go
  pkg/manager/component/utils.go
Labels: size/M

#23 add kapacitor
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/climc.go
  pkg/manager/component/component.go
  pkg/manager/component/kapacitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/utils.go
Labels: size/L

#25 add host-image
  pkg/manager/component/component.go
  pkg/manager/component/host.go
Labels: size/S

#29 host /opt/cloud use bidirectional propagate
  pkg/manager/component/utils.go
Labels: size/XS

#27 set workloads spec image when defaults init
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/utils.go
Labels: size/M

#26 add report-usage cronjob component
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmon-report-usage.go
  pkg/manager/component/component.go
Labels: size/M

#24 Feature: Add Esxi Agent
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/esxi.go
Labels: size/L

#30 host container don't mount kernel modules
  pkg/manager/component/utils.go
Labels: size/S

#31 fix(notify): Change the Verify Email Address
  pkg/manager/component/notify.go
Labels: size/XS

#32 set baremetal update strategy recreate
  pkg/manager/component/baremetal.go
  pkg/manager/component/component.go
Labels: size/S
