Repository yunionio/cloudpods-operator, pull requests merged in 2020-04, with the labels that each got.

#89 create region firstly when setup keystone
  pkg/controller/onecloud_control.go
Labels: size/XS

#92 initContainers use same ImagePullPolicy
  pkg/manager/component/component.go
  pkg/manager/component/keystone.go
Labels: size/XS

#93 Automated cherry pick of #92: initContainers use same ImagePullPolicy
  pkg/manager/component/component.go
  pkg/manager/component/keystone.go
Labels: size/XS

#94 Automated cherry pick of #92: initContainers use same ImagePullPolicy
  pkg/manager/component/component.go
  pkg/manager/component/keystone.go
Labels: size/XS

#95 fix var run mount propagation
  pkg/manager/component/utils.go
Labels: lgtm, size/M

#96 Automated cherry pick of #95: fix var run mount propagation
  pkg/manager/component/utils.go
Labels: size/M

#97 Automated cherry pick of #95: fix var run mount propagation
  pkg/manager/component/utils.go
Labels: size/M

#98 faature: support nocloud. no not merge into master
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/component.go
  pkg/manager/component/register.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
Labels: size/L

#99 apigateway: cors hosts
  pkg/manager/component/apigateway.go
Labels: approved, lgtm, size/XS

#100 add nginx command
  pkg/manager/component/web.go
Labels: lgtm, size/XS

#104 Automated cherry pick of #103: add sockio web location
  pkg/manager/component/web.go
Labels: size/S

#106 添加cronjob StartingDeadlineSeconds 参数
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/component.go
Labels: size/XS

#107 Automated cherry pick of #106: 添加cronjob StartingDeadlineSeconds 参数
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/component.go
Labels: size/XS

#108 Automated cherry pick of #106: 添加cronjob StartingDeadlineSeconds 参数
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/component.go
Labels: size/XS

#110 do not always sync configmap
  pkg/manager/component/component.go
Labels: size/S

#111 Automated cherry pick of #110: do not always sync configmap
  pkg/manager/component/component.go
Labels: size/S

#112 Automated cherry pick of #110: do not always sync configmap
  pkg/manager/component/component.go
Labels: size/S

#125 Automated cherry pick of #124: fix api_server url
  pkg/controller/onecloud_control.go
Labels: size/M

#117 Automated cherry pick of #116: create etcd service
  pkg/manager/component/etcd.go
Labels: size/S

#120 fix cronjob update
  pkg/manager/component/utils.go
Labels: size/XS

#121 Automated cherry pick of #120: fix cronjob update
  pkg/manager/component/utils.go
Labels: size/XS

#123 Automated cherry pick of #120: fix cronjob update
  pkg/manager/component/utils.go
Labels: size/XS

#122 Automated cherry pick of #120: fix cronjob update
  pkg/manager/component/utils.go
Labels: size/XS

#124 fix api_server url
  pkg/controller/onecloud_control.go
Labels: size/M

#118 host: tell sdnagent to use common.conf
  pkg/manager/component/host.go
Labels: size/XS

#119 Automated cherry pick of #118: host: tell sdnagent to use common.conf
  pkg/manager/component/host.go
Labels: size/XS

#132 auto mount etcd tls
  pkg/apis/constants/constants.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/utils.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionconf.go
Labels: lgtm, size/M
