Repository yunionio/cloudpods-operator, pull requests merged in 2020-07, with the labels that each got.

#199 add billingtask component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/billingtask.go
  pkg/manager/component/component.go
Labels: size/M

#194 cloudmon as deployment
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/base_control.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cronjob_control.go
  pkg/controller/deployment_control.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudmon_ping.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/cloudmon_report_server.go
  pkg/manager/component/cloudmon_report_usage.go
  pkg/manager/component/component.go
Labels: lgtm, size/XL

#197 Automated cherry pick of #194: cloudmon as deployment
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/base_control.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cronjob_control.go
  pkg/controller/deployment_control.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudmon_ping.go
  pkg/manager/component/cloudmon_report_host.go
  pkg/manager/component/cloudmon_report_server.go
  pkg/manager/component/cloudmon_report_usage.go
  pkg/manager/component/component.go
Labels: size/XL

#196 Automated cherry pick of #195: host image component set default toleration
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#195 host image component set default toleration
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#200 fix billingtask deployment config
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/billingtask.go
Labels: size/S

#198 service etcd client disable tolerate unready pod options
  pkg/manager/component/etcd.go
Labels: size/M

#201 Automated cherry pick of #198: service etcd client disable unready client
  pkg/manager/component/etcd.go
Labels: size/M

#203 add check if cronjob exist
  pkg/manager/component/cloudmon.go
Labels: size/S

#204 Automated cherry pick of #203: add check if cronjob exist
  pkg/manager/component/cloudmon.go
Labels: size/S

#205 cloudmon deployment increase [rds redis oss] monitor information
  pkg/manager/component/cloudmon.go
Labels: lgtm, size/S

#209 fix glance pvc name
  pkg/manager/component/glance.go
Labels: size/M

#211 Automated cherry pick of #209: fix glance pvc name
  pkg/manager/component/glance.go
Labels: size/M

#212 fix set pvc name
  pkg/manager/component/baremetal.go
  pkg/manager/component/esxi.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
Labels: size/XS

#213 Automated cherry pick of #212: fix set pvc name
  pkg/manager/component/baremetal.go
  pkg/manager/component/esxi.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
Labels: size/XS

#215 Automated cherry pick of #214: 修复系统报警规则重复创建的问题
  pkg/util/onecloud/onecloud.go
Labels: size/XS

#214 修复系统报警规则重复创建的问题
  pkg/util/onecloud/onecloud.go
Labels: size/XS

#216 fix: member policy requires member role
  pkg/controller/onecloud_policy.go
Labels: size/XS

#217 Automated cherry pick of #216: fix: member policy requires member role
  pkg/controller/onecloud_policy.go
Labels: size/XS

#218 bugfix: recreate pods on pvc not local path
  pkg/manager/component/baremetal.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
Labels: size/S

#219 Automated cherry pick of #218: recreate pods on pvc not local path
  pkg/manager/component/baremetal.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/meter.go
Labels: size/S

#220 fix: apigateway totp should default on
  pkg/manager/component/apigateway.go
Labels: size/XS

#222 bugfix: fix etcd member count
  pkg/apis/constants/constants.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
  pkg/manager/component/region.go
Labels: size/M

#226 Automated cherry pick of #222: fix etcd member count
  pkg/apis/constants/constants.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
  pkg/manager/component/region.go
Labels: size/M

#227 Automated cherry pick of #222: fix etcd member count
  pkg/apis/constants/constants.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
  pkg/manager/component/region.go
Labels: size/M

#221 Automated cherry pick of #220: fix: apigateway totp should default on
  pkg/manager/component/apigateway.go
Labels: size/XS

#230 yunionagent: update content
  pkg/controller/onecloud_control.go
Labels: size/XS

#231 Automated cherry pick of #230: yunionagent: update content
  pkg/controller/onecloud_control.go
Labels: size/XS

#232 Automated cherry pick of #230: yunionagent: update content
  pkg/controller/onecloud_control.go
Labels: size/XS

#233 fix: nocloudmeter
  pkg/manager/component/meter.go
Labels: size/M

#228 调整统一监控 系统报警规则的注入配置
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#229 Automated cherry pick of #228: 调整统一监控 系统报警规则的注入配置
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M
