Repository yunionio/cloudpods-operator, pull requests merged in 2020-02, with the labels that each got.

#33 add generate baremetal prepare option
  pkg/manager/component/region.go
Labels: size/M

#40 Add ovn, vpc, sdn related components
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/utils.go
  pkg/manager/component/vpcagent.go
Labels: lgtm, size/L

#41 Automated cherry pick of #40: cluster_control: fix UpdateCluster error handling
  go.mod
  go.sum
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/utils.go
  pkg/manager/component/vpcagent.go
Labels: size/L
