Repository yunionio/cloudpods-operator, pull requests merged in 2020-10, with the labels that each got.

#283 regiondns: configmap: quash trailing spaces
  pkg/manager/component/regiondns.go
Labels: approved, lgtm, size/XS

#286 Automated cherry pick of #283: regiondns: configmap: quash trailing spaces
  pkg/manager/component/regiondns.go
Labels: approved, lgtm, size/XS

#284 Automated cherry pick of #283: regiondns: configmap: quash trailing spaces
  pkg/manager/component/regiondns.go
Labels: approved, lgtm, size/XS

#285 Automated cherry pick of #283: regiondns: configmap: quash trailing spaces
  pkg/manager/component/regiondns.go
Labels: approved, lgtm, size/XS

#287 Automated cherry pick of #283: regiondns: configmap: quash trailing spaces
  pkg/manager/component/regiondns.go
Labels: approved, lgtm

#294 set image default policy to if not present
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#295 Automated cherry pick of #294: set image default policy to if not present
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#296 Automated cherry pick of #294: set image default policy to if not present
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#292 feat: add webhook plugin for notify
  pkg/manager/component/notify.go
Labels: size/XS

#293 Automated cherry pick of #292: feat: add webhook plugin for notify
  pkg/manager/component/notify.go
Labels: size/XS

#298 monitor: inject smart_device and host_raid alert rule
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#299 Automated cherry pick of #298: monitor: inject smart_device and host_raid alert rule
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#302 bugfix: monitor initInfo
  pkg/controller/onecloud_control.go
Labels: size/XS

#305 Automated cherry pick of #302: bugfix:
  pkg/controller/onecloud_control.go
Labels: size/XS

#306 Automated cherry pick of #302: bugfix:
  pkg/controller/onecloud_control.go
Labels: size/XS

#307 add qcloud rds crond
  pkg/manager/component/cloudmon.go
Labels: size/XS

#308 Automated cherry pick of #307: add qcloud rds crond
  pkg/manager/component/cloudmon.go
Labels: size/XS

#309 modify commonalert init policy
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#310 Automated cherry pick of #309: modify commonalert init policy :
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#311 Automated cherry pick of #309: modify commonalert init policy :
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/L

#312 qcloud add redis crond
  pkg/manager/component/cloudmon.go
Labels: size/XS

#313 Automated cherry pick of #312: qcloud add redis crond
  pkg/manager/component/cloudmon.go
Labels: size/XS

#314 更新 nginx 配置以防 dos 攻击
  pkg/manager/component/web.go
Labels: lgtm, size/S

#315 Automated cherry pick of #314: 更新 nginx 配置以防 dos 攻击
  pkg/manager/component/web.go
Labels: size/S

#316 Automated cherry pick of #314: 更新 nginx 配置以防 dos 攻击
  pkg/manager/component/web.go
Labels: size/S
