Repository yunionio/cloudpods-operator, pull requests merged in 2021-06, with the labels that each got.

#443 fix(minio): disable minio component when status is fail
  pkg/util/onecloud/onecloud.go
Labels: size/S

#444 Automated cherry pick of #443: fix(minio): disable minio component when status is fail
  pkg/util/onecloud/onecloud.go
Labels: size/S

#445 feat: support jdcloud monitor metric
  pkg/manager/component/cloudmon.go
Labels: size/XS

#446 fix: raid plugin: raid status fix
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#447 Automated cherry pick of #446: fix: raid plugin: raid status fix
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#448 Automated cherry pick of #446: fix: raid plugin: raid status fix
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#449 fix: cloudmon timeout fix
  pkg/manager/component/cloudmon.go
Labels: size/S

#450 Automated cherry pick of #449: fix: cloudmon timeout fix
  pkg/manager/component/cloudmon.go
Labels: size/S

#451 Automated cherry pick of #449: fix: cloudmon timeout fix
  pkg/manager/component/cloudmon.go
Labels: size/S

#452 Automated cherry pick of #449: fix: cloudmon timeout fix
  pkg/manager/component/cloudmon.go
Labels: size/S

#453 fix: update raid-plugin image tag
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#455 Automated cherry pick of #453: fix: update raid-plugin image tag
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#454 Automated cherry pick of #453: fix: update raid-plugin image tag
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#456 fix: update system commonalert param
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#457 Automated cherry pick of #456: fix: update system commonalert param
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#458 Automated cherry pick of #456: fix: update system commonalert param
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/M

#462 fix(glance): s3 endpoint should use domain resolve
  pkg/manager/component/glance.go
Labels: approved, size/XS

#463 Automated cherry pick of #462: fix(glance): s3 endpoint should use domain resolve
  pkg/manager/component/glance.go
Labels: approved, size/XS

#459 fix: update process.total name
  pkg/controller/onecloud_control.go
Labels: size/XS

#460 Automated cherry pick of #459: fix: update process.total name
  pkg/controller/onecloud_control.go
Labels: size/XS

#461 Automated cherry pick of #459: fix: update process.total name
  pkg/controller/onecloud_control.go
Labels: size/XS
