Repository yunionio/cloudpods-operator, pull requests merged in 2021-08, with the labels that each got.

#475 feat(cloudmon): support HuaweiCloudStack metric
  pkg/manager/component/cloudmon.go
Labels: size/XS

#476 Automated cherry pick of #475: feat(cloudmon): support HuaweiCloudStack metric
  pkg/manager/component/cloudmon.go
Labels: size/XS

#479 Automated cherry pick of #478: feat(operator): set default resources limits for each component
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/esxi.go
  pkg/manager/component/glance.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionconf.go
Labels: size/L, lgtm, approved

#480 feat(crd): support inject imagePullSecrets
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/component.go
Labels: size/L, approved

#481 Automated cherry pick of #480: feat(crd): support inject imagePullSecrets
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/component.go
Labels: size/L, approved

#482 Automated cherry pick of #480: feat(crd): support inject imagePullSecrets
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/component.go
Labels: size/L
