Repository yunionio/cloudpods-operator, pull requests merged in 2021-03, with the labels that each got.

#415 fix: default policy name should be separated by dash
  go.mod
  go.sum
  pkg/controller/onecloud_policy.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
Labels: size/L

#416 Automated cherry pick of #415: fix: default policy name should be separated by dash
  Makefile
  go.mod
  go.sum
  pkg/controller/onecloud_policy.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
Labels: size/L

#417 Automated cherry pick of #415: fix: default policy name should be separated by dash
  go.mod
  go.sum
  pkg/controller/onecloud_policy.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
Labels: size/L

#420 feat(build): support multi arch docker image
  Makefile
  cmd/onecloud-operator/main.go
  scripts/docker_push.sh
Labels: size/M

#421 Automated cherry pick of #420: feat(build): support multi arch docker image
  Makefile
  cmd/onecloud-operator/main.go
  scripts/docker_push.sh
Labels: size/M

#422 Automated cherry pick of #420: feat(build): support multi arch docker image
  Makefile
  cmd/onecloud-operator/main.go
  scripts/docker_push.sh
Labels: size/M

#427 fix(monitor): raid卡监控规则status过滤参数调整
  pkg/controller/onecloud_control.go
Labels: size/XS

#428 Automated cherry pick of #427: fix(monitor): raid卡监控规则status过滤参数调整
  pkg/controller/onecloud_control.go
Labels: size/XS

#429 Automated cherry pick of #427: fix(monitor): raid卡监控规则status过滤参数调整
  pkg/controller/onecloud_control.go
Labels: size/XS

#432 fix: access_url of common service config
  pkg/controller/onecloud_control.go
Labels: size/M

#433 Automated cherry pick of #432: fix: access_url of common service config
  pkg/controller/onecloud_control.go
Labels: size/M

#434 Automated cherry pick of #432: fix: access_url of common service config
  pkg/controller/onecloud_control.go
Labels: size/M

#435 Automated cherry pick of #432: fix: access_url of common service config
  pkg/controller/onecloud_control.go
Labels: size/M

#436 Automated cherry pick of #432: fix: access_url of common service config
  pkg/controller/onecloud_control.go
Labels: size/M
