Repository yunionio/cloudpods-operator, pull requests merged in 2021-07, with the labels that each got.

#464 update manifest version to v3.7.5
  OWNERS
  manifests/example-onecloud-cluster.yaml
  manifests/onecloud-operator.yaml
Labels: approved, size/XS

#465 feat：add jdcloud rds metric
  pkg/manager/component/cloudmon.go
Labels: size/XS

#466 feat(cloudmon): update cloudmon component image info
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/cloudmon.go
Labels: size/S

#471 Automated cherry pick of #466: feat(cloudmon): update cloudmon component image info
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/cloudmon.go
Labels: size/S
