Repository yunionio/cloudpods-operator, pull requests merged in 2021-11, with the labels that each got.

#507 update vendor for master 20211113
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/quota/doc.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/quota/mod_quotas.go
Labels: size/M

#506 feat(monitor): update default alert level
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#510 update vendor at master
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guest_disk.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/blkid.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/cheksum.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/doc.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/exists.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/fasthash.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/fileutils.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/partition.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/seeker.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/size.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/sparse.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/writable_others.go
  vendor/yunion.io/x/onecloud/pkg/util/fileutils2/writable_windows.go
  vendor/yunion.io/x/onecloud/pkg/util/netutils2/netutils.go
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/XXL
