Repository yunionio/cloudpods-operator, pull requests merged in 2021-01, with the labels that each got.

#380 Feat/zxc monitor update master
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon.go
Labels: size/M

#381 Automated cherry pick of #380: feat(cloudmon): add cloudmon alertrecord crontab
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon.go
Labels: size/M

#382 Automated cherry pick of #380: feat(cloudmon): add cloudmon alertrecord crontab
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudmon.go
Labels: size/M

#383 fix(cloudmon): crond commond fmt err
  pkg/manager/component/cloudmon.go
Labels: size/XS

#384 Automated cherry pick of #383: fix(cloudmon): crond commond fmt err
  pkg/manager/component/cloudmon.go
Labels: size/XS

#385 Automated cherry pick of #383: fix(cloudmon): crond commond fmt err
  pkg/manager/component/cloudmon.go
Labels: size/XS

#389 apigateway: allow setting cors_hosts
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/apigateway.go
Labels: size/M

#390 Automated cherry pick of #389: apigateway: allow setting cors_hosts
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/apigateway.go
Labels: size/M

#391 Automated cherry pick of #389: apigateway: allow setting cors_hosts
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/apigateway.go
Labels: size/M

#392 apigateway: cors: rename spec field name to corsHosts
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/XS

#393 Automated cherry pick of #392: apigateway: cors: rename spec field name to corsHosts
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/XS

#394 Automated cherry pick of #392: apigateway: cors: rename spec field name to corsHosts
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/XS

#395 fix: fail to init policy
  pkg/controller/onecloud_control.go
  pkg/controller/onecloud_policy.go
Labels: size/S

#396 Automated cherry pick of #395: fix: fail to init policy
  pkg/controller/onecloud_control.go
  pkg/controller/onecloud_policy.go
Labels: size/S
