Repository yunionio/cloudpods-operator, pull requests merged in 2022-11, with the labels that each got.

#722 fix: add cloudmon service
  pkg/manager/component/cloudmon.go
Labels: size/XS

#724 feature: add region-ee image name
  pkg/apis/constants/constants.go
  pkg/manager/component/region.go
Labels: size/XS

#727 fix(README): how to install code-generator
  README.md
  hack/generate-groups.sh
Labels: size/M

#728 Automated cherry pick of #727: fix(README): how to install code-generator
  README.md
  hack/generate-groups.sh
Labels: size/M

#729 fix: clickhouse db not init properly
  pkg/manager/component/cloudevent.go
  pkg/manager/component/component.go
  pkg/manager/component/glance.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/webconsole.go
Labels: size/S

#730 Automated cherry pick of #729: fix: clickhouse db not init properly
  pkg/manager/component/cloudevent.go
  pkg/manager/component/component.go
  pkg/manager/component/glance.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/webconsole.go
Labels: size/S

#731 fix: enable clickhouse when host is set
  pkg/manager/component/component.go
Labels: size/XS

#733 Automated cherry pick of #731: fix: enable clickhouse when host is set
  pkg/manager/component/component.go
Labels: size/XS
