Repository yunionio/cloudpods-operator, pull requests merged in 2022-08, with the labels that each got.

#692 fix(etcd): update etcd size by master node count
  pkg/manager/component/etcd.go
Labels: size/S

#693 Automated cherry pick of #692: fix(etcd): update etcd size by master node count
  pkg/manager/component/etcd.go
Labels: size/S

#694 Automated cherry pick of #692: fix(etcd): update etcd size by master node count
  pkg/manager/component/etcd.go
Labels: size/S

#698 fix: hide immature components
  pkg/manager/component/yunionconf.go
Labels: size/S

#699 Automated cherry pick of #698: fix: hide immature components
  pkg/manager/component/yunionconf.go
Labels: size/S

#702 fix(operator): yunionagent port
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#703 Automated cherry pick of #702: fix(operator): yunionagent port
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#704 fix(etcd): enable fix etcd size
  pkg/manager/component/etcd.go
Labels: size/S

#705 Automated cherry pick of #704: fix(etcd): enable fix etcd size
  pkg/manager/component/etcd.go
Labels: size/S

#706 Automated cherry pick of #704: fix(etcd): enable fix etcd size
  pkg/manager/component/etcd.go
Labels: size/S

#700 fix: remove apiversion from session
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/glance.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/onecloud/cmd/climc/shell/watch.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guestnetwork.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/networkaddress.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/mergeconf.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/syncman/watcher/watcher.go
  vendor/yunion.io/x/onecloud/pkg/cloudmon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/hostman/guestman/desc/desc.go
  vendor/yunion.io/x/onecloud/pkg/hostman/guestman/desc/doc.go
  vendor/yunion.io/x/onecloud/pkg/hostman/guestman/desc/pci.go
  vendor/yunion.io/x/onecloud/pkg/hostman/hostdeployer/apis/utils.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/README.md
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/session_cache.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/appoptions.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/misc.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/modules.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/stats.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybook_reference.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybooks.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybooks_v2.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/cloudproxy/common.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_capabilities.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_dynamicschedtags.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_externalprojects.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_metadatas.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_schedpolicies.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_sshkeypairs.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_tasks.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/k8s/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_logs.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/monitor/mod_commonalert.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/monitor/mod_migration_alert.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/quota/mod_quotas.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/register.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/scheduler/mod_scheduler.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/yunionconf/mod_parameters.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/onecloud/pkg/util/netutils2/netutils.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XXL

#701 Automated cherry pick of #700: fix: remove apiversion from session
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/glance.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/onecloud/cmd/climc/shell/watch.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/networkaddress.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/mergeconf.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/syncman/watcher/watcher.go
  vendor/yunion.io/x/onecloud/pkg/cloudmon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/session_cache.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/appoptions.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/misc.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/modules.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/stats.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybook_reference.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybooks.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/ansible/mod_ansibleplaybooks_v2.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/cloudproxy/common.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_capabilities.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_dynamicschedtags.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_externalprojects.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_metadatas.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_schedpolicies.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_sshkeypairs.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/compute/mod_tasks.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/k8s/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/managers.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_logs.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/monitor/mod_commonalert.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/monitor/mod_migration_alert.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/quota/mod_quotas.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/register.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/scheduler/mod_scheduler.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/yunionconf/mod_parameters.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/L
