Repository yunionio/cloudpods-operator, pull requests merged in 2022-07, with the labels that each got.

#664 feat: add report service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/component.go
  pkg/manager/component/report.go
Labels: size/L

#665 Automated cherry pick of #664: feat: add report service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/component.go
  pkg/manager/component/report.go
Labels: size/L

#667 Automated cherry pick of #666: fix: report db setting
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/S

#670 feat(grafana): db config
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/monitor_stack.go
  pkg/util/onecloud/kubeserver.go
Labels: size/M

#672 Automated cherry pick of #670: feat(grafana): db config
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/monitor_stack.go
  pkg/util/onecloud/kubeserver.go
Labels: size/M

#673 feat(operator): enable leader election option
  cmd/onecloud-operator/main.go
Labels: size/M

#674 Automated cherry pick of #673: feat(operator): enable leader election option
  cmd/onecloud-operator/main.go
Labels: size/M

#676 fix: report sync
  pkg/manager/component/report.go
Labels: size/XS

#677 Automated cherry pick of #676: fix: report sync
  pkg/manager/component/report.go
Labels: size/XS

#680 Automated cherry pick of #678: fix: not set setupOneStackInitialized
  pkg/manager/component/yunionconf.go
Labels: size/XS

#678 fix: not set setupOneStackInitialized
  pkg/manager/component/yunionconf.go
Labels: size/XS

#681 fix(operator): sync grafana db
  pkg/manager/component/monitor_stack.go
Labels: size/S

#682 Automated cherry pick of #681: fix(operator): sync grafana db
  pkg/manager/component/monitor_stack.go
Labels: size/S
