Repository yunionio/cloudpods-operator, pull requests merged in 2022-04, with the labels that each got.

#581 Automated cherry pick of #580: fix(meter): node affinity
  pkg/manager/component/meter.go
Labels: size/S

#580 fix(meter): node affinity
  pkg/manager/component/meter.go
Labels: size/S

#582 Automated cherry pick of #580: fix(meter): node affinity
  pkg/manager/component/meter.go
Labels: size/S

#583 fix: nginx api export timeout
  pkg/manager/component/web.go
Labels: size/XS

#584 Automated cherry pick of #583: fix: nginx api export timeout
  pkg/manager/component/web.go
Labels: size/XS

#585 Automated cherry pick of #583: fix: nginx api export timeout
  pkg/manager/component/web.go
Labels: size/XS

#588 update vendor onecloud@release/3.9
  go.mod
  go.sum
  vendor/github.com/moul/http2curl/.gitignore
  vendor/github.com/moul/http2curl/.travis.yml
  vendor/github.com/moul/http2curl/Makefile
  vendor/github.com/moul/http2curl/README.md
  vendor/modules.txt
  vendor/moul.io/http2curl/v2/.gitattributes
  vendor/moul.io/http2curl/v2/.gitignore
  vendor/moul.io/http2curl/v2/.releaserc.js
  vendor/moul.io/http2curl/v2/AUTHORS
  vendor/moul.io/http2curl/v2/COPYRIGHT
  vendor/moul.io/http2curl/v2/LICENSE-APACHE
  vendor/moul.io/http2curl/v2/LICENSE-MIT
  vendor/moul.io/http2curl/v2/Makefile
  vendor/moul.io/http2curl/v2/README.md
  vendor/moul.io/http2curl/v2/doc.go
  vendor/moul.io/http2curl/v2/go.mod
  vendor/moul.io/http2curl/v2/go.sum
  vendor/moul.io/http2curl/v2/http2curl.go
  vendor/moul.io/http2curl/v2/rules.mk
  vendor/yunion.io/x/onecloud/locales/locales.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/handlerinfo.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/dnszone.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/consts.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/errors.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/cloudaccounts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/metadata.go
  vendor/yunion.io/x/onecloud/pkg/util/httputils/httputils.go
Labels: size/XXL

#587 update onecloud@master vendor
  go.mod
  go.sum
  vendor/github.com/moul/http2curl/.gitignore
  vendor/github.com/moul/http2curl/.travis.yml
  vendor/github.com/moul/http2curl/Makefile
  vendor/github.com/moul/http2curl/README.md
  vendor/modules.txt
  vendor/moul.io/http2curl/v2/.gitattributes
  vendor/moul.io/http2curl/v2/.gitignore
  vendor/moul.io/http2curl/v2/.releaserc.js
  vendor/moul.io/http2curl/v2/AUTHORS
  vendor/moul.io/http2curl/v2/COPYRIGHT
  vendor/moul.io/http2curl/v2/LICENSE-APACHE
  vendor/moul.io/http2curl/v2/LICENSE-MIT
  vendor/moul.io/http2curl/v2/Makefile
  vendor/moul.io/http2curl/v2/README.md
  vendor/moul.io/http2curl/v2/doc.go
  vendor/moul.io/http2curl/v2/go.mod
  vendor/moul.io/http2curl/v2/go.sum
  vendor/moul.io/http2curl/v2/http2curl.go
  vendor/moul.io/http2curl/v2/rules.mk
  vendor/yunion.io/x/onecloud/locales/locales.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/handlerinfo.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/dnszone.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/consts.go
  vendor/yunion.io/x/onecloud/pkg/httperrors/errors.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modulebase/base.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/cloudaccounts.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/metadata.go
  vendor/yunion.io/x/onecloud/pkg/util/httputils/httputils.go
Labels: size/XXL

#589 update vendor 20220405 qj
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#590 Automated cherry pick of #589: update vendor 20220405 qj
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#592 Host image resolv
  pkg/manager/component/host-image.go
Labels: size/M

#594 Automated cherry pick of #592: fix(host-image): dns not resolv on debian
  pkg/manager/component/host-image.go
Labels: size/M

#593 Automated cherry pick of #592: fix(host-image): dns not resolv on debian
  pkg/manager/component/host-image.go
Labels: size/M

#597 fix(notify): enable websocket plugin when ee enabled
  pkg/manager/component/notify.go
Labels: size/XS

#598 Automated cherry pick of #597: fix(notify): enable websocket plugin when ee enabled
  pkg/manager/component/notify.go
Labels: size/XS

#595 update vendor 20220413
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/encrypt.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/domain.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/user.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/appsrv.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/lockman/lockman.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/transport.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/onecloud/pkg/logger/extern/syslog.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/identity/mod_credentials.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/cloudaccounts.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/net_topology_pro.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/tag_base.go
  vendor/yunion.io/x/onecloud/pkg/util/ctx/context.go
  vendor/yunion.io/x/onecloud/pkg/util/ctx/doc.go
  vendor/yunion.io/x/onecloud/pkg/util/encode/doc.go
  vendor/yunion.io/x/onecloud/pkg/util/encode/encode.go
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/L

#596 Automated cherry pick of #595: update vendor 20220413
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudaccount.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/encrypt.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/domain.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/user.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/appsrv.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/lockman/lockman.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/transport.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/onecloud/pkg/logger/extern/syslog.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/mcclient.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/identity/mod_credentials.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/cloudaccounts.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/esxi/net_topology_pro.go
  vendor/yunion.io/x/onecloud/pkg/multicloud/tag_base.go
  vendor/yunion.io/x/onecloud/pkg/util/ctx/context.go
  vendor/yunion.io/x/onecloud/pkg/util/ctx/doc.go
  vendor/yunion.io/x/onecloud/pkg/util/encode/doc.go
  vendor/yunion.io/x/onecloud/pkg/util/encode/encode.go
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/L

#600 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/disk.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/externalproject.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/assignments.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/user.go
  vendor/yunion.io/x/onecloud/pkg/cloudmon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#591 feat: hyper packed image support
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/L

#611 fix: always sync db user
  pkg/manager/component/utils.go
Labels: size/S

#612 Automated cherry pick of #611: fix: always sync db user
  pkg/manager/component/utils.go
Labels: size/S

#613 Automated cherry pick of #611: fix: always sync db user
  pkg/manager/component/utils.go
Labels: size/S
