Repository yunionio/cloudpods-operator, pull requests merged in 2022-06, with the labels that each got.

#638 fix(host-image): update DefaultHostImageTag to v1.0.4
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#639 Automated cherry pick of #638: fix(host-image): update DefaultHostImageTag to v1.0.4
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#647 fix: minor fixes for 3.8
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/executor/client/client.go
Labels: size/S

#640 feature: add disable_local_vpc, enable_cloud_net, enable_s3gateway var
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/host.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/vpcagent.go
Labels: size/L

#641 Automated cherry pick of #640: feature: add disable_local_vpc, enable_cloud_net, enable_s3gateway var
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/host.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/vpcagent.go
Labels: size/L

#645 Automated cherry pick of #640: feature: add disable_local_vpc, enable_cloud_net, enable_s3gateway var
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/vpcagent.go
Labels: size/L

#649 fix(telegraf): use release-1.19.2-0 image
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#651 Automated cherry pick of #649: fix(telegraf): use release-1.19.2-0 image
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#652 Automated cherry pick of #649: fix(telegraf): use release-1.19.2-0 image
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#653 fix: add hostagent options: hostCpuPassthough and defaultQemuVersion
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/host.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/api.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_account.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_database.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dnszone.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticcache.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticip.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/schedtag.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/secgroup.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/serversku.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/storage.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/hostman/system_service/telegraf.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/index.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XL

#654 Automated cherry pick of #653: fix: add hostagent options: hostCpuPassthough and defaultQemuVersion
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/host.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/api.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_account.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dbinstance_database.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/dnszone.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticcache.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticip.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/schedtag.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/secgroup.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/serversku.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/storage.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/onecloud/pkg/hostman/options/options.go
  vendor/yunion.io/x/onecloud/pkg/hostman/system_service/telegraf.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/session.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/index.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XL

#655 etcd-operator: remove fix etcd size, pod anti affinity required
  pkg/manager/component/etcd.go
Labels: size/S

#657 Automated cherry pick of #655: etcd-operator: remove fix etcd size, pod anti affinity required
  pkg/manager/component/etcd.go
Labels: size/S

#656 Automated cherry pick of #655: etcd-operator: remove fix etcd size, pod anti affinity required
  pkg/manager/component/etcd.go
Labels: size/S

#658 fix: update DefaultTelegrafRaidImageTag to release-1.6.4
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS
