Repository yunionio/cloudpods-operator, pull requests merged in 2022-01, with the labels that each got.

#528 fix: etcd manager wrong references
  pkg/manager/component/baremetal.go
  pkg/manager/component/etcd.go
  pkg/manager/component/itsm.go
Labels: size/S

#529 Automated cherry pick of #528: fix: etcd manager wrong references
  pkg/manager/component/baremetal.go
  pkg/manager/component/etcd.go
  pkg/manager/component/itsm.go
Labels: size/S

#532 Automated cherry pick of #531: fix: aliyun v1.20 deployment
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/etcd.go
  pkg/manager/component/web.go
  pkg/util/k8sutil/k8sutil.go
Labels: size/M

#533 fix: move ee overview and docs to internal nginx config
  pkg/manager/component/web.go
Labels: size/M

#534 Automated cherry pick of #533: fix: move ee overview and docs to internal nginx config
  pkg/manager/component/web.go
Labels: size/M

#535 fix(vendor): update jsonutils
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
Labels: size/XS

#536 Automated cherry pick of #535: fix(vendor): update jsonutils
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
Labels: size/XS

#537 fix(cloudmon): fixed cloudmon deployment resourece.limit info
  pkg/manager/component/cloudmon.go
Labels: size/XS

#538 Automated cherry pick of #537: fix(cloudmon): fixed cloudmon deployment resourece.limit info
  pkg/manager/component/cloudmon.go
Labels: size/XS

#540 Automated cherry pick of #538: fix(cloudmon): fixed cloudmon deployment resourece.limit info
  pkg/manager/component/cloudmon.go
Labels: size/XS

#541 feat(operator): support disableResourceMangement
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/component.go
Labels: size/M

#542 Automated cherry pick of #541: feat(operator): support disableResourceMangement
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/component.go
Labels: size/M

#543 Automated cherry pick of #541: feat(operator): support disableResourceMangement
  go.mod
  go.sum
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/onecloud/v1alpha1/zz_generated.defaults.go
  pkg/manager/component/component.go
Labels: size/M

#544 Fix 3 8 schedtask type
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
Labels: size/XS

#545 fix(operator): remove mount /proc volume
  pkg/manager/component/utils.go
Labels: size/M

#546 Automated cherry pick of #545: fix(operator): remove mount /proc volume
  pkg/manager/component/utils.go
Labels: size/M

#547 Automated cherry pick of #545: fix(operator): remove mount /proc volume
  pkg/manager/component/utils.go
Labels: size/M
