Repository yunionio/cloudpods-operator, pull requests merged in 2022-12, with the labels that each got.

#736 fix: only filter Aliyun brand cloudaccount balance
  pkg/controller/onecloud_control.go
Labels: size/S

#737 Automated cherry pick of #736: fix: only filter Aliyun brand cloudaccount balance
  pkg/controller/onecloud_control.go
Labels: size/S

#738 Automated cherry pick of #736: fix: only filter Aliyun brand cloudaccount balance
  pkg/controller/onecloud_control.go
Labels: size/S

#734 fix: support vpcagent service listening port
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/region.go
  pkg/manager/component/vpcagent.go
Labels: size/M

#735 Automated cherry pick of #734: fix: support vpcagent service listening port
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/region.go
  pkg/manager/component/vpcagent.go
Labels: size/M

#739 fix(operator): check glance service config
  pkg/manager/component/glance.go
Labels: size/S

#740 Automated cherry pick of #739: fix(operator): check glance service config
  pkg/manager/component/glance.go
Labels: size/S

#741 Automated cherry pick of #739: fix(operator): check glance service config
  pkg/manager/component/glance.go
Labels: size/S

#742 fix(operator): remove created pvc of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#743 Automated cherry pick of #742: fix(operator): remove created pvc of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#744 Automated cherry pick of #742: fix(operator): remove created pvc of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#745 feat: add cloudmon-ee image name
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/region.go
Labels: size/S

#746 Automated cherry pick of #745: feat: add cloudmon-ee image name
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/region.go
Labels: size/S

#747 fix(operator): telegraf component uses release-1.19.2-1 tag
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/XS

#750 Automated cherry pick of #747: fix(operator): telegraf component uses release-1.19.2-1 tag which contains tini as entrypoint
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/XS

#749 Automated cherry pick of #747: fix(operator): telegraf component uses release-1.19.2-1 tag which contains tini as entrypoint
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/XS

#748 Automated cherry pick of #747: fix(operator): telegraf component uses release-1.19.2-1 tag which contains tini as entrypoint
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/XS

#752 Automated cherry pick of #751: fix(operator): components of kubserver use oc.spec.imageRepository
  pkg/controller/onecloud_control.go
  pkg/manager/component/monitor_stack.go
  pkg/util/onecloud/kubeserver.go
Labels: size/M

#753 Automated cherry pick of #751: fix(operator): components of kubserver use oc.spec.imageRepository
  pkg/controller/onecloud_control.go
  pkg/manager/component/monitor_stack.go
  pkg/util/onecloud/kubeserver.go
Labels: size/M

#751 fix(operator): components of kubserver use oc.spec.imageRepository
  pkg/controller/onecloud_control.go
  pkg/manager/component/monitor_stack.go
  pkg/util/onecloud/kubeserver.go
Labels: size/M

#755 feat: add stop-services flag
  cmd/onecloud-operator/main.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
Labels: size/S

#756 Automated cherry pick of #755: feat: add stop-services flag
  cmd/onecloud-operator/main.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
Labels: size/S

#757 Automated cherry pick of #755: feat: add stop-services flag
  cmd/onecloud-operator/main.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
Labels: size/S

#758 fix(operator): not remove cloud affinity of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#759 Automated cherry pick of #758: fix(operator): not remove cloud affinity of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#760 Automated cherry pick of #758: fix(operator): not remove cloud affinity of esxi-agent
  pkg/manager/component/esxi.go
Labels: size/XS

#761 fix: stop services recreate daemonset
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
Labels: size/S

#762 Automated cherry pick of #761: fix: stop services recreate daemonset
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
Labels: size/S

#763 Automated cherry pick of #761: fix: stop services recreate daemonset
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
Labels: size/S
