Repository yunionio/cloudpods-operator, pull requests merged in 2023-02, with the labels that each got.

#800 feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#801 Automated cherry pick of #800: feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#802 Automated cherry pick of #800: feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#803 fix(operator): adjust web component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#804 Automated cherry pick of #803: fix(operator): adjust web component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#805 Automated cherry pick of #803: fix(operator): adjust web component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#806 feat(operator): clear component's specified image info
  cmd/onecloud-operator/main.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/M

#807 Automated cherry pick of #806: feat(operator): clear component's specified image info
  cmd/onecloud-operator/main.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/M

#808 Automated cherry pick of #806: feat(operator): clear component's specified image info
  cmd/onecloud-operator/main.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/M

#813 Automated cherry pick of #812: feat: update k8s dependencies to release-1.19
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/OpenAPIv2/README.md
  vendor/github.com/googleapis/gnostic/OpenAPIv2/openapi-2.0.json
Labels: size/XXL

#814 Automated cherry pick of #812: feat: update k8s dependencies to release-1.19
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/OpenAPIv2/README.md
  vendor/github.com/googleapis/gnostic/OpenAPIv2/openapi-2.0.json
Labels: size/XXL

#820 feat(web): support use http
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/web.go
Labels: size/M

#821 Automated cherry pick of #820: feat(web): support use http
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/web.go
Labels: size/M

#822 Automated cherry pick of #820: feat(web): support use http
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/web.go
Labels: size/M

#827 fix(operator): phase of cloudproxy
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudproxyserver.go
Labels: size/M

#828 Automated cherry pick of #827: fix(operator): phase of cloudproxy
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudproxyserver.go
Labels: size/M

#829 Automated cherry pick of #827: fix(operator): phase of cloudproxy
  pkg/controller/onecloud_control.go
  pkg/manager/component/cloudproxyserver.go
Labels: size/M

#830 fix(operator): update vendor to fix duplicate-task-worker-count
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/baremetal/options/options.go
  vendor/yunion.io/x/onecloud/pkg/hostman/hostdeployer/apis/utils.go
Labels: size/M

#832 Automated cherry pick of #830: fix(operator): update vendor to fix duplicate-task-worker-count
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cdn.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/project.go
  vendor/yunion.io/x/onecloud/pkg/baremetal/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/tablespec.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cdn_domains.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/kube_clusters.go
  vendor/yunion.io/x/onecloud/pkg/hostman/hostdeployer/apis/utils.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/L

#831 Automated cherry pick of #830: fix(operator): update vendor to fix duplicate-task-worker-count
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cdn.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/project.go
  vendor/yunion.io/x/onecloud/pkg/baremetal/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/db_dispatcher.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/tablespec.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cdn_domains.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancerbackends.go
  vendor/yunion.io/x/onecloud/pkg/hostman/hostdeployer/apis/utils.go
  vendor/yunion.io/x/onecloud/pkg/keystone/options/options.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/L

#833 Automated cherry pick of #792: fix: request with app name operator
  pkg/controller/onecloud_control.go
Labels: size/S

#835 fix(operator): auth with operator source
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go
  vendor/yunion.io/x/onecloud/pkg/util/rbacutils/results.go
  vendor/yunion.io/x/onecloud/pkg/util/tagutils/tagset.go
  vendor/yunion.io/x/onecloud/pkg/util/tagutils/tagsetlist.go
Labels: size/L

#836 Automated cherry pick of #835: fix(operator): auth with operator source
  go.mod
  go.sum
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guestdisks.go
  vendor/yunion.io/x/onecloud/pkg/hostman/guestfs/fsdriver/linux.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go
  vendor/yunion.io/x/onecloud/pkg/util/rbacutils/results.go
  vendor/yunion.io/x/onecloud/pkg/util/tagutils/tagset.go
  vendor/yunion.io/x/onecloud/pkg/util/tagutils/tagsetlist.go
Labels: size/L

#838 feat(operator): disable raid plugin by default
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/telegraf.go
Labels: size/S

#839 Automated cherry pick of #838: feat(operator): disable raid plugin by default
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/telegraf.go
Labels: size/S

#840 Automated cherry pick of #838: feat(operator): disable raid plugin by default
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/telegraf.go
Labels: size/S

#841 feat(operator): support etcd nodeport
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
Labels: size/M

#842 Automated cherry pick of #841: feat(operator): support etcd nodeport
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
Labels: size/M

#843 Automated cherry pick of #841: feat(operator): support etcd nodeport
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/etcd.go
Labels: size/M

#845 fix(operator): setup etcd services
  pkg/manager/component/etcd.go
Labels: size/M

#847 Automated cherry pick of #845: fix(operator): setup etcd services
  pkg/manager/component/etcd.go
Labels: size/M
