Repository yunionio/cloudpods-operator, pull requests merged in 2023-12, with the labels that each got.

#988 feat: webconsole support guacamole
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/webconsole.go
Labels: size/M

#989 Automated cherry pick of #988: feat: webconsole support guacamole
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/component/webconsole.go
Labels: size/M

#994 fix(victoria-metrics): use v1.95.1
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#995 Automated cherry pick of #994: fix(victoria-metrics): use v1.95.1
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#996 Automated cherry pick of #994: fix(victoria-metrics): use v1.95.1
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#997 feat: add extdb service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/extdb.go
Labels: size/L

#998 Automated cherry pick of #997: feat: add extdb service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/extdb.go
Labels: size/L

#1003 Automated cherry pick of #1002: fix(operator): enable host-deployer for all product versions
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1004 Automated cherry pick of #1002: fix(operator): enable host-deployer for all product versions
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1000 fix: add webconsole sftp
  pkg/service-init/component/web.go
Labels: size/S

#1001 Automated cherry pick of #1000: fix: add webconsole sftp
  pkg/service-init/component/web.go
Labels: size/S

#1006 Automated cherry pick of #1005: ffix(host-deployer): host deployer use host network
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1007 Automated cherry pick of #1005: ffix(host-deployer): host deployer use host network
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1005 ffix(host-deployer): host deployer use host network
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1008 fix(operator): generate configmap for host-deployer when PV is CMP
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1009 Automated cherry pick of #1008: fix(operator): generate configmap for host-deployer when PV is CMP
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1010 Automated cherry pick of #1008: fix(operator): generate configmap for host-deployer when PV is CMP
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1011 fix: grant clieckhouse MYSQL privilleges
  pkg/util/clickhouse/clickhouse.go
Labels: size/XS

#1012 Automated cherry pick of #1011: fix: grant clieckhouse MYSQL privilleges
  pkg/util/clickhouse/clickhouse.go
Labels: size/XS

#1013 feat(service-init): host-deployer and esxi-agent
  pkg/controller/onecloud_control.go
  pkg/manager/component/esxi.go
  pkg/service-init/component/component.go
  pkg/service-init/component/esxi.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
Labels: size/L

#1014 Automated cherry pick of #1013: feat(service-init): host-deployer and esxi-agent
  pkg/controller/onecloud_control.go
  pkg/manager/component/esxi.go
  pkg/service-init/component/component.go
  pkg/service-init/component/esxi.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
Labels: size/L

#1015 Automated cherry pick of #1013: feat(service-init): host-deployer and esxi-agent
  pkg/controller/onecloud_control.go
  pkg/manager/component/esxi.go
  pkg/service-init/component/component.go
  pkg/service-init/component/esxi.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
Labels: size/L

#1016 feat(operator): add ee biling service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/billing.go
  pkg/manager/component/component.go
Labels: size/L

#1017 Automated cherry pick of #1016: feat(operator): add ee biling service
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/billing.go
  pkg/manager/component/component.go
Labels: size/L
