Repository yunionio/cloudpods-operator, pull requests merged in 2023-11, with the labels that each got.

#975 fix(operator): smart_device health status alerting should use health_ok field
  pkg/controller/onecloud_control.go
Labels: size/S

#976 Automated cherry pick of #975: fix(operator): smart_device health status alerting should use health_ok field
  pkg/controller/onecloud_control.go
Labels: size/S

#977 Automated cherry pick of #975: fix(operator): smart_device health status alerting should use health_ok field
  pkg/controller/onecloud_control.go
Labels: size/S

#978 Automated cherry pick of #975: fix(operator): smart_device health status alerting should use health_ok field
  pkg/controller/onecloud_control.go
Labels: size/S

#973 fix: auto enable volcengine
  pkg/service-init/component/yunoinconf.go
Labels: size/XS

#974 Automated cherry pick of #973: fix: auto enable volcengine
  pkg/service-init/component/yunoinconf.go
Labels: size/XS

#980 fix(compose): add cloudid service
  pkg/manager/component/cloudid.go
  pkg/service-init/component/cloudid.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/doc.go
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/options.go
Labels: size/L

#981 Automated cherry pick of #980: fix(compose): add cloudid service
  pkg/manager/component/cloudid.go
  pkg/service-init/component/cloudid.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/doc.go
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/options.go
Labels: size/L

#982 Automated cherry pick of #980: fix(compose): add cloudid service
  pkg/manager/component/cloudid.go
  pkg/service-init/component/cloudid.go
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/doc.go
  vendor/yunion.io/x/onecloud/pkg/cloudid/options/options.go
Labels: size/L

#983 fix(operator): cloudid unused import
  pkg/manager/component/cloudid.go
Labels: size/XS

#979 feat(operator): add victoria-metrics component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/victoriametrics.go
  pkg/service-init/component/influxdb.go
  pkg/service-init/component/victoriametrics.go
Labels: size/L

#986 Automated cherry pick of #979: feat(operator): add victoria-metrics component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/victoriametrics.go
  pkg/service-init/component/influxdb.go
  pkg/service-init/component/victoriametrics.go
Labels: size/L
