Repository yunionio/cloudpods-operator, pull requests merged in 2023-04, with the labels that each got.

#887 operator： restart region on influxdb setup
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/service-init/component/influxdb.go
Labels: size/M

#890 Automated cherry pick of #887: operator： restart region on influxdb setup
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/service-init/component/influxdb.go
Labels: size/M

#889 Automated cherry pick of #887: operator： restart region on influxdb setup
  pkg/controller/onecloud_control.go
  pkg/manager/component/component.go
  pkg/service-init/component/influxdb.go
Labels: size/M

#893 Automated cherry pick of #892: Automated cherry pick of #891: fix(operator): adjust component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/S

#892 Automated cherry pick of #891: fix(operator): adjust component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/S

#891 fix(operator): adjust component sync order
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/S

#894 fix(operator): init Keystone firstly
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#896 Automated cherry pick of #894: fix(operator): init Keystone firstly
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS
