Repository yunionio/cloudpods-operator, pull requests merged in 2023-08, with the labels that each got.

#932 feat: support bastion component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/bastionhost.go
  pkg/manager/component/component.go
Labels: size/L

#933 Automated cherry pick of #932: feat: support bastion component
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/bastionhost.go
  pkg/manager/component/component.go
Labels: size/L

#934 fix: add cloudmux
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/cloudmux.go
  pkg/manager/component/component.go
Labels: size/L

#936 fix: avoid upload occur 408 code
  pkg/service-init/component/web.go
Labels: size/XS

#937 Automated cherry pick of #936: fix: avoid upload occur 408 code
  pkg/service-init/component/web.go
Labels: size/XS

#940 fix: bastion host name
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/XS

#941 Automated cherry pick of #940: fix: bastion host name
  pkg/apis/onecloud/v1alpha1/types.go
Labels: size/XS

#942 fix: specify sysadmin project domain name
  pkg/controller/onecloud_control.go
Labels: size/XS

#944 Automated cherry pick of #942: fix: specify sysadmin project domain name
  pkg/controller/onecloud_control.go
Labels: size/XS

#943 Automated cherry pick of #942: fix: specify sysadmin project domain name
  pkg/controller/onecloud_control.go
Labels: size/XS

#945 fix: fixed web image name
  pkg/manager/component/web.go
Labels: size/S

#947 Automated cherry pick of #945: fix: fixed web image name
  pkg/manager/component/web.go
Labels: size/S

#946 Automated cherry pick of #945: fix: fixed web image name
  pkg/manager/component/web.go
Labels: size/S

#948 fix: cloudmux repo
  .github/workflows/docker.yml
  pkg/manager/component/cloudmux.go
  scripts/docker_push.sh
Labels: size/M

#949 Automated cherry pick of #948: fix: cloudmux repo
  .github/workflows/docker.yml
  pkg/manager/component/cloudmux.go
  scripts/docker_push.sh
Labels: size/M

#953 fix: nginx timeout syntax
  pkg/service-init/component/web.go
Labels: size/XS

#954 Automated cherry pick of #953: fix: nginx timeout syntax
  pkg/service-init/component/web.go
Labels: size/XS

#950 fix: remove apsara
  pkg/service-init/component/yunoinconf.go
Labels: size/XS

#951 Automated cherry pick of #950: fix: remove apsara
  pkg/service-init/component/yunoinconf.go
Labels: size/XS

#952 Automated cherry pick of #950: fix: remove apsara
  pkg/service-init/component/yunoinconf.go
Labels: size/XS

#955 fix(operator): ensure global-settings is updated
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#956 Automated cherry pick of #955: fix(operator): ensure global-settings is updated
  pkg/service-init/component/yunoinconf.go
Labels: size/M
