Repository yunionio/cloudpods-operator, pull requests merged in 2023-03, with the labels that each got.

#854 fix(operator): update telegraf image tag to release-1.19.2-2
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#857 fix: add db support to autoupdate
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/autoupdate.go
Labels: size/S

#858 Automated cherry pick of #857: fix: add db support to autoupdate
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/autoupdate.go
Labels: size/S

#859 Automated cherry pick of #857: fix: add db support to autoupdate
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/autoupdate.go
Labels: size/S

#863 feat: notify support useHyperImage
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#864 Automated cherry pick of #863: feat: notify support useHyperImage
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#865 fix(operator): notify with initContainers
  pkg/manager/component/notify.go
Labels: size/S

#868 chore: update ovn image tag
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#869 manual cherrypick: chore: update ovn image tag
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#874 Automated cherry pick of #873: fix(operator): useHyperImage of host, sdnagent and lbagent
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/S

#870 fix: autoupdate update configmap automatically
  pkg/manager/component/autoupdate.go
Labels: size/S

#872 Automated cherry pick of #870: fix: autoupdate update configmap automatically
  pkg/manager/component/autoupdate.go
Labels: size/S

#875 add host health, allow update ds update strategy
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
Labels: size/L

#876 Automated cherry pick of #875: add host health, allow update ds update strategy
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/component.go
  pkg/manager/component/host.go
Labels: size/L

#885 feat(service-init): add cloudmon service
  pkg/manager/component/cloudmon.go
  pkg/service-init/component/cloudmon.go
Labels: size/M

#886 Automated cherry pick of #885: feat(service-init): add cloudmon service
  pkg/manager/component/cloudmon.go
  pkg/service-init/component/cloudmon.go
Labels: size/M
