Repository yunionio/cloudpods-operator, pull requests merged in 2023-01, with the labels that each got.

#764 fix: region set imageName when empty ONLY
  hack/cherry_pick_pull.sh
  pkg/manager/component/region.go
Labels: size/M

#765 Automated cherry pick of #764: fix: region set imageName when empty ONLY
  hack/cherry_pick_pull.sh
  pkg/manager/component/region.go
Labels: size/M

#766 fix(glance): set enable_remote_executor to false when ProductVersion is CMP
  pkg/manager/component/glance.go
Labels: size/S

#767 Automated cherry pick of #766: fix(glance): set enable_remote_executor to false when ProductVersion is CMP
  pkg/manager/component/glance.go
Labels: size/S

#768 Automated cherry pick of #766: fix(glance): set enable_remote_executor to false when ProductVersion is CMP
  pkg/manager/component/glance.go
Labels: size/S

#774 Automated cherry pick of #772: fix(operator): check mysql peer node's sync status
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/L

#773 Automated cherry pick of #772: fix(operator): check mysql peer node's sync status
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/L

#775 fix: update vendor at 20230107
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/appsrv/workers.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
Labels: size/M

#783 Automated cherry pick of #782: fix(operator): handle region ee image
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/region.go
Labels: size/XS

#784 fix(operator): handle cloudmon edition image
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#786 fix(operator): notify-plugins not useHyperImage
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#789 fix(operator): delete deployments
  pkg/controller/deployment_control.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/component.go
  pkg/manager/component/s3gateway.go
Labels: size/S

#792 fix: request with app name operator
  pkg/controller/onecloud_control.go
Labels: size/S

#793 Automated cherry pick of #792: fix: request with app name operator
  pkg/controller/onecloud_control.go
Labels: size/S

#794 fix(operator): remove pvc of meter component
  pkg/manager/component/meter.go
Labels: size/S

#795 Automated cherry pick of #794: fix(operator): remove pvc of meter component
  pkg/manager/component/meter.go
Labels: size/S

#796 Automated cherry pick of #794: fix(operator): remove pvc of meter component
  pkg/manager/component/meter.go
Labels: size/S

#798 Automated cherry pick of #797: fix(operator): set EDITOR=vim env for climc component
  pkg/manager/component/climc.go
Labels: size/XS

#797 fix(operator): set EDITOR=vim env for climc component
  pkg/manager/component/climc.go
Labels: size/XS

#799 Automated cherry pick of #797: fix(operator): set EDITOR=vim env for climc component
  pkg/manager/component/climc.go
Labels: size/XS
