Repository yunionio/cloudpods-operator, pull requests merged in 2024-06, with the labels that each got.

#1088 feat: turn on vmware and proxmox feature for edge product version
  pkg/service-init/component/yunoinconf.go
Labels: size/S

#1090 Automated cherry pick of #1088: feat: turn on vmware and proxmox feature for edge product version
  pkg/service-init/component/yunoinconf.go
Labels: size/S

#1070 fix: mysql check user update
  pkg/util/mysql/mysql.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#1071 Automated cherry pick of #1070: fix: mysql check user update
  pkg/util/mysql/mysql.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#1072 Automated cherry pick of #1070: fix: mysql check user update
  pkg/util/mysql/mysql.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#1098 fix(operator): enable esxi agent for Edge ProductVersion
  pkg/manager/component/esxi.go
Labels: size/XS

#1100 Automated cherry pick of #1098: fix(operator): enable esxi agent for Edge ProductVersion
  pkg/manager/component/esxi.go
Labels: size/XS

#1099 Automated cherry pick of #1098: fix(operator): enable esxi agent for Edge ProductVersion
  pkg/manager/component/esxi.go
Labels: size/XS

#1097 Automated cherry pick of #1070: fix: mysql check user update
  pkg/util/mysql/mysql.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#1101 Automated cherry pick of #1070: fix: mysql check user update
  pkg/util/mysql/mysql.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/genpolicy.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_policies.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#1091 feat: init baremetal service
  cmd/compose-service-init/main.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/baremetal.go
  pkg/service-init/cluster/cluster.go
  pkg/service-init/component/baremetal.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
  pkg/service-init/component/prepare.go
  pkg/service-init/component/yunoinconf.go
Labels: size/L

#1104 Automated cherry pick of #1091: feat: init baremetal service
  cmd/compose-service-init/main.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/baremetal.go
  pkg/service-init/cluster/cluster.go
  pkg/service-init/component/baremetal.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
  pkg/service-init/component/prepare.go
  pkg/service-init/component/yunoinconf.go
Labels: size/L

#1105 Automated cherry pick of #1091: feat: init baremetal service
  cmd/compose-service-init/main.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/baremetal.go
  pkg/service-init/cluster/cluster.go
  pkg/service-init/component/baremetal.go
  pkg/service-init/component/glance.go
  pkg/service-init/component/host-deployer.go
  pkg/service-init/component/prepare.go
  pkg/service-init/component/yunoinconf.go
Labels: size/L

#1106 fix(operator): make webconsole created before web
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#1107 Automated cherry pick of #1106: fix(operator): make webconsole created before web
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS

#1108 Automated cherry pick of #1106: fix(operator): make webconsole created before web
  pkg/controller/cluster/onecloud_cluster_control.go
Labels: size/XS
