Repository yunionio/cloudpods-operator, pull requests merged in 2024-11, with the labels that each got.

#1151 clean DefaultOnecloudRegionDNSDomain
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/regiondns.go
Labels: size/S

#1152 Automated cherry pick of #1151: clean DefaultOnecloudRegionDNSDomain
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/regiondns.go
Labels: size/S

#1153 Automated cherry pick of #1151: clean DefaultOnecloudRegionDNSDomain
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/regiondns.go
Labels: size/S

#1154 Automated cherry pick of #1151: clean DefaultOnecloudRegionDNSDomain
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/regiondns.go
Labels: size/S

#1158 Swordqiu hotfix/qj sync disable service
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/apimap.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/bastionhost.go
  pkg/manager/component/billing.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudmux.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/echarts-ssr.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/extdb.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/lbagent.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/monitor_stack.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/report.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduledtask.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/victoriametrics.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
  pkg/manager/manager.go
  pkg/util/onecloud/onecloud.go
Labels: size/XL

#1159 Automated cherry pick of #1158: Swordqiu hotfix/qj sync disable service
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/apimap.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/bastionhost.go
  pkg/manager/component/billing.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudmux.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/echarts-ssr.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/extdb.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/lbagent.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/monitor_stack.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/report.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduledtask.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/victoriametrics.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
  pkg/manager/manager.go
  pkg/util/onecloud/onecloud.go
Labels: size/XL

#1160 Automated cherry pick of #1158: Swordqiu hotfix/qj sync disable service
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/manager/component/ansibleserver.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/apimap.go
  pkg/manager/component/autoupdate.go
  pkg/manager/component/baremetal.go
  pkg/manager/component/bastionhost.go
  pkg/manager/component/billing.go
  pkg/manager/component/climc.go
  pkg/manager/component/cloudevent.go
  pkg/manager/component/cloudid.go
  pkg/manager/component/cloudmon.go
  pkg/manager/component/cloudmux.go
  pkg/manager/component/cloudnetserver.go
  pkg/manager/component/cloudproxyserver.go
  pkg/manager/component/component.go
  pkg/manager/component/devtool.go
  pkg/manager/component/echarts-ssr.go
  pkg/manager/component/esxi.go
  pkg/manager/component/etcd.go
  pkg/manager/component/extdb.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/influxdb.go
  pkg/manager/component/itsm.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/lbagent.go
  pkg/manager/component/logger.go
  pkg/manager/component/meter.go
  pkg/manager/component/monitor.go
  pkg/manager/component/monitor_stack.go
  pkg/manager/component/notify.go
  pkg/manager/component/ovn-north.go
  pkg/manager/component/region.go
  pkg/manager/component/regiondns.go
  pkg/manager/component/report.go
  pkg/manager/component/s3gateway.go
  pkg/manager/component/scheduledtask.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/service_operator.go
  pkg/manager/component/suggestion.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/victoriametrics.go
  pkg/manager/component/vpcagent.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
  pkg/manager/manager.go
  pkg/util/onecloud/onecloud.go
Labels: size/XL

#1161 feat: set telegraf image to release-1.19.2-5
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1162 Automated cherry pick of #1161: feat: set telegraf image to release-1.19.2-5
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1163 Automated cherry pick of #1161: feat: set telegraf image to release-1.19.2-5
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1164 fix(suggestion): isolate suggestion database
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/suggestion.go
Labels: size/S

#1166 Automated cherry pick of #1164: fix(suggestion): isolate suggestion database
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/suggestion.go
Labels: size/S

#1167 feat: update telegraf image to release-1.19.2-7
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/S

#1169 Automated cherry pick of #1167: feat: update telegraf image to release-1.19.2-7
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/S

#1170 Automated cherry pick of #1167: feat: update telegraf image to release-1.19.2-7
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/telegraf.go
Labels: size/S

#1171 fix(operator): skipping setup yunionagent if service is exist
  pkg/service-init/component/yunoinconf.go
Labels: size/S

#1173 Automated cherry pick of #1171: fix(operator): skipping setup yunionagent if service is exist
  pkg/service-init/component/yunoinconf.go
Labels: size/S

#1172 Automated cherry pick of #1171: fix(operator): skipping setup yunionagent if service is exist
  pkg/service-init/component/yunoinconf.go
Labels: size/S

#1175 fix(operator): dead lock on yunionconf sync yunionagent service
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster_control.go
  pkg/manager/component/etcd.go
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#1176 Automated cherry pick of #1175: fix(operator): dead lock on yunionconf sync yunionagent service
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster_control.go
  pkg/manager/component/etcd.go
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#1178 Automated cherry pick of #1175: fix(operator): dead lock on yunionconf sync yunionagent service
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/cluster/onecloud_cluster_control.go
  pkg/controller/cluster_control.go
  pkg/manager/component/etcd.go
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#1179 feat: update telegraf version to release-1.19.2-8
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1180 Automated cherry pick of #1179: feat: update telegraf version to release-1.19.2-8
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1181 Automated cherry pick of #1179: feat: update telegraf version to release-1.19.2-8
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1182 Automated cherry pick of #1179: feat: update telegraf version to release-1.19.2-8
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1183 feat: update telegraf version to release-1.19.2-9
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1184 Automated cherry pick of #1183: feat: update telegraf version to release-1.19.2-9
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1185 Automated cherry pick of #1183: feat: update telegraf version to release-1.19.2-9
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1186 Automated cherry pick of #1183: feat: update telegraf version to release-1.19.2-9
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1138 feat: support ce/support edition
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/utils.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
  pkg/service-init/component/web.go
Labels: size/M

#1187 Automated cherry pick of #1138: feat: support ce/support edition
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/utils.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
  pkg/service-init/component/web.go
Labels: size/M

#1188 Automated cherry pick of #1138: feat: support ce/support edition
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/utils.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
  pkg/service-init/component/web.go
Labels: size/M

#1189 Automated cherry pick of #1138: feat: support ce/support edition
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/utils.go
  pkg/manager/component/web.go
  pkg/manager/component/yunionagent.go
  pkg/service-init/component/web.go
Labels: size/M

#1190 fix(operator): not disable yunionagent when edition is ce/support
  pkg/manager/component/yunionagent.go
Labels: size/XS

#1191 Automated cherry pick of #1190: fix(operator): not disable yunionagent when edition is ce/support
  pkg/manager/component/yunionagent.go
Labels: size/XS

#1192 Automated cherry pick of #1190: fix(operator): not disable yunionagent when edition is ce/support
  pkg/manager/component/yunionagent.go
Labels: size/XS

#1193 Automated cherry pick of #1190: fix(operator): not disable yunionagent when edition is ce/support
  pkg/manager/component/yunionagent.go
Labels: size/XS

#1194 Revert "fix(suggestion): isolate suggestion database"
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/suggestion.go
Labels: size/S

#1195 Automated cherry pick of #1194: Revert "fix(suggestion): isolate suggestion database"
  pkg/apis/constants/constants.go
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/suggestion.go
Labels: size/S

#1196 fix: defaults of suggestion
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
Labels: size/XS

#1197 Automated cherry pick of #1196: fix: defaults of suggestion
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
Labels: size/XS

#1198 add bond alert
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#1200 Automated cherry pick of #1198: add bond alert
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#1199 Automated cherry pick of #1198: add bond alert
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#1201 Automated cherry pick of #1198: add bond alert
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S

#1202 Automated cherry pick of #1198: add bond alert
  pkg/controller/onecloud_control.go
  pkg/util/onecloud/onecloud.go
Labels: size/S
