Repository yunionio/cloudpods-operator, pull requests merged in 2024-07, with the labels that each got.

#1109 fix: update vendor 20240703
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/api.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/doc.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/profiles.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/container.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticips_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/alertrecord.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/consts/db.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/virtualresource.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/changes.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/mergeconf.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/types/ipmi.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/baremetal/doc.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/baremetal/profiles.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cloudaccount_vmware.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/containers.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/elasticips.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_convert.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guestdrivers.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guests.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/initdb.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/isolated_devices.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/natgateways.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/networks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/vpcs.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/waf_regexsets.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/compute/eips.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/compute/server_pod.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/compute/servers.go
  vendor/yunion.io/x/onecloud/pkg/monitor/tsdb/models.go
  vendor/yunion.io/x/onecloud/pkg/util/logclient/consts.go
  vendor/yunion.io/x/onecloud/pkg/util/logclient/consts_i18n.go
  vendor/yunion.io/x/onecloud/pkg/util/netutils2/netutils.go
  vendor/yunion.io/x/onecloud/pkg/util/procutils/remote_stat.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: lgtm, size/XXL

#1111 Automated cherry pick of #1109: fix: update vendor 20240703
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/doc.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/profiles.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/baremetal/zz_generated.model.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/elasticips_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/apis/identity/consts.go
  vendor/yunion.io/x/onecloud/pkg/apis/monitor/alertrecord.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/consts/db.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/virtualresource.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/changes.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/mergeconf.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/options/options.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/types/ipmi.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/baremetal/doc.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/baremetal/profiles.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cloudaccount_vmware.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/elasticips.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_convert.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guests.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/initdb.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/natgateways.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/networks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/vpcs.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/waf_regexsets.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/compute/eips.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/options/compute/servers.go
  vendor/yunion.io/x/onecloud/pkg/monitor/tsdb/models.go
  vendor/yunion.io/x/onecloud/pkg/util/logclient/consts.go
  vendor/yunion.io/x/onecloud/pkg/util/logclient/consts_i18n.go
  vendor/yunion.io/x/onecloud/pkg/util/procutils/remote_stat.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/XXL

#1112 Automated cherry pick of #1039: fix(operator): use telegraf-raid-plugin:release-1.6.5
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1114 fix(operator): ensure cloud user of host deployer
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1115 Automated cherry pick of #1114: fix(operator): ensure cloud user of host deployer
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1116 Automated cherry pick of #1114: fix(operator): ensure cloud user of host deployer
  pkg/manager/component/host-deployer.go
Labels: size/XS

#1129 fix: update vendor 3.9 20240729
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/guests.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/host.go
  vendor/yunion.io/x/onecloud/pkg/keystone/locale/predefined_yaml.go
  vendor/yunion.io/x/onecloud/pkg/webconsole/options/options.go
Labels: size/L
