Repository yunionio/cloudpods-operator, pull requests merged in 2024-04, with the labels that each got.

#1058 fix: update user password only when -sync-user
  pkg/service-init/component/cloudutil.go
  pkg/service-init/component/dbutil.go
  pkg/util/clickhouse/clickhouse.go
  pkg/util/dameng/dameng.go
  pkg/util/dbutil/db.go
  pkg/util/mysql/mysql.go
Labels: size/L

#1059 Automated cherry pick of #1058: fix: update user password only when -sync-user
  pkg/service-init/component/cloudutil.go
  pkg/service-init/component/dbutil.go
  pkg/util/clickhouse/clickhouse.go
  pkg/util/dameng/dameng.go
  pkg/util/dbutil/db.go
  pkg/util/mysql/mysql.go
Labels: size/L

#1060 Automated cherry pick of #1058: fix: update user password only when -sync-user
  pkg/service-init/component/cloudutil.go
  pkg/service-init/component/dbutil.go
  pkg/util/clickhouse/clickhouse.go
  pkg/util/dbutil/db.go
  pkg/util/mysql/mysql.go
Labels: size/M

#1062 fix: simplify mounts of telegraf container
  pkg/manager/component/telegraf.go
Labels: size/L

#1064 Automated cherry pick of #1063: fix: simplify mounts of telegraf @v3.11
  pkg/manager/component/telegraf.go
Labels: size/M

#1063 fix: simplify mounts of telegraf @v3.11
  pkg/manager/component/telegraf.go
Labels: size/M

#1065 fix(host-image): mount dev dir
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/S

#1066 Automated cherry pick of #1065: fix(host-image): mount dev dir
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/S

#1067 Automated cherry pick of #1065: fix(host-image): mount dev dir
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/S

#1068 Automated cherry pick of #1065: fix(host-image): mount dev dir
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/S

#1069 解决3.8开源版自动启用autoupdate的 bug（预期不启用）
  pkg/manager/component/autoupdate.go
Labels: size/XS

#1074 Automated cherry pick of #1073: fix(host-image): update host-image image version
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1075 Automated cherry pick of #1073: fix(host-image): update host-image image version
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1076 Automated cherry pick of #1073: fix(host-image): update host-image image version
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS

#1077 Automated cherry pick of #1073: fix(host-image): update host-image image version
  pkg/apis/onecloud/v1alpha1/defaults.go
Labels: size/XS
