Repository yunionio/cloudpods-operator, pull requests merged in 2025-03, with the labels that each got.

#1237 fix: enable etcd tls by default
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/certs/manager.go
  pkg/manager/component/etcd.go
  pkg/manager/component/utils.go
  pkg/service-init/component/prepare.go
Labels: size/S

#1239 Automated cherry pick of #1237: fix: enable etcd tls by default
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/controller/onecloud_control.go
  pkg/manager/certs/manager.go
  pkg/manager/component/etcd.go
  pkg/manager/component/utils.go
  pkg/service-init/component/prepare.go
Labels: size/S

#1240 fix(operator): change disk alert policy
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
Labels: size/M

#1241 Automated cherry pick of #1240: fix(operator): change disk alert policy
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
Labels: size/M

#1242 Automated cherry pick of #1240: fix(operator): change disk alert policy
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
Labels: size/M

#1243 fix(operator): set victoria-metrics tlsCipherSuites
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#1245 Automated cherry pick of #1243: fix(operator): set victoria-metrics tlsCipherSuites
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#1247 Automated cherry pick of #1246: fix(etcd): enable shareProcessNamespace resolve zombie processes
  pkg/manager/component/etcd.go
Labels: size/XS

#1246 fix(etcd): enable shareProcessNamespace resolve zombie processes
  pkg/manager/component/etcd.go
Labels: size/XS
