Repository yunionio/cloudpods-operator, pull requests merged in 2025-02, with the labels that each got.

#1220 fix(host): configureable host maxUnavailable and augment FailureThreshold count
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/host.go
Labels: lgtm, size/XS

#1221 Automated cherry pick of #1220: fix(host): configureable host maxUnavailable and augment FailureThreshold count
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/host.go
Labels: size/XS

#1222 fix(operator): change level of bond_slave status alert to important
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#1223 Automated cherry pick of #1222: fix(operator): change level of bond_slave status alert to important
  pkg/apis/onecloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/onecloud_control.go
Labels: size/XS

#1224 feat(operator): add secure property of ObjectStoreConfig
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/util/onecloud/kubeserver.go
Labels: size/XS

#1225 Automated cherry pick of #1224: feat(operator): add secure property of ObjectStoreConfig
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/util/onecloud/kubeserver.go
Labels: size/XS

#1203 fix(host-image): fit host-image use nbd export disks
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/M

#1226 Automated cherry pick of #1203: fix(host-image): fit host-image use nbd export disks
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/manager/component/host-image.go
  pkg/manager/component/utils.go
Labels: size/M

#1228 feat(system): add system.load1_pcore alerting policy
  pkg/controller/onecloud_control.go
Labels: size/S

#1229 Automated cherry pick of #1228: feat(system): add system.load1_pcore alerting policy
  pkg/controller/onecloud_control.go
Labels: size/S

#1230 Automated cherry pick of #1228: feat(system): add system.load1_pcore alerting policy
  pkg/controller/onecloud_control.go
Labels: size/S

#1232 Automated cherry pick of #1231: feat(operator): add LightEdge product version
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/climc.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/victoriametrics.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#1233 Automated cherry pick of #1231: feat(operator): add LightEdge product version
  pkg/apis/onecloud/v1alpha1/defaults.go
  pkg/apis/onecloud/v1alpha1/types.go
  pkg/manager/component/apigateway.go
  pkg/manager/component/climc.go
  pkg/manager/component/etcd.go
  pkg/manager/component/glance.go
  pkg/manager/component/host-deployer.go
  pkg/manager/component/host-image.go
  pkg/manager/component/host.go
  pkg/manager/component/keystone.go
  pkg/manager/component/kubeserver.go
  pkg/manager/component/logger.go
  pkg/manager/component/monitor.go
  pkg/manager/component/notify.go
  pkg/manager/component/region.go
  pkg/manager/component/scheduler.go
  pkg/manager/component/sync.go
  pkg/manager/component/telegraf.go
  pkg/manager/component/victoriametrics.go
  pkg/manager/component/web.go
  pkg/manager/component/webconsole.go
  pkg/manager/component/yunionagent.go
  pkg/manager/component/yunionconf.go
  pkg/service-init/component/yunoinconf.go
Labels: size/M

#1234 feat(operator): add pprofAuthKey option to victoriametrics
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#1235 Automated cherry pick of #1234: feat(operator): add pprofAuthKey option to victoriametrics
  pkg/manager/component/victoriametrics.go
Labels: size/XS

#1236 Automated cherry pick of #1234: feat(operator): add pprofAuthKey option to victoriametrics
  pkg/manager/component/victoriametrics.go
Labels: size/XS
